#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const dataPath = path.join(__dirname, "..", "data", "pauli-sol-planner.json");
const data = JSON.parse(fs.readFileSync(dataPath, "utf8"));
const { applyClassification } = require("./sol_taxonomy");
const { applyPlanningStructure } = require("./planning_structure");

const evidenceSources = [
  {title:"A Little Guide for Teachers: Cognitive Load Theory - Greg Ashman",url:"https://www.sagepub.com/shop/buy-a-book/a-little-guide-for-teachers-cognitive-load-theory-1-283309",role:"Arbetsminne, genomarbetade exempel och gradvis minskat stöd"},
  {title:"Embedded Formative Assessment, Second Edition - Dylan Wiliam",url:"https://hawkerbrownlow.com/products/embedded-formative-assessment-second-edition",role:"Kontroll av förståelse och nästa undervisningsbeslut"},
  {title:"Why Don't Students Like School?, Second Edition - Daniel T. Willingham",url:"https://www.wiley-vch.de/en/areas-interest/humanities-social-sciences/education-12ed/k-12-general-12ed1/teaching-learning-k-12-12ed13/why-don-39-t-students-like-school-978-1-119-71566-5",role:"Förkunskaper, minne, tänkande och övning"},
  {title:"The Science of Learning, Second Edition - Deans for Impact",url:"https://www.deansforimpact.org/resources/the-science-of-learning/",role:"Förkunskaper, minne, övning och självreglering"}
];

const rationale = {
  "Aktiv återkallning":"hämtar fram nödvändiga förkunskaper utan stöd",
  "Modellering":"gör expertens val och kontrollfrågor synliga",
  "Genomarbetade exempel":"minskar onödig belastning medan en ny procedur byggs upp",
  "Kontrasterande exempel":"gör den avgörande skillnaden mellan närliggande fall synlig",
  "Felanalys":"låter eleven diagnostisera en missuppfattning i stället för att bara rätta svaret",
  "Självförklaring":"kopplar handlingar och textdrag till underliggande principer",
  "Gradvis minskat stöd":"flyttar ansvaret stegvis från lärarens modell till eleven",
  "Utspridd övning":"prövar om kunskapen kan återkallas efter ett mellanrum",
  "Blandad övning":"kräver att eleven väljer metod utifrån problemets struktur",
  "Överföring":"prövar samma kunskap i en ny situation"
};

function item(prefix, index, area, text, p) {
  const methods = p.methods || ["Aktiv återkallning","Modellering","Kontrasterande exempel","Överföring"];
  const steps = [
    `Starta med en individuell återkallning: ${p.recall}`,
    `Läraren tänker högt i ett genomarbetat exempel: ${p.model}`,
    `Eleverna arbetar parvis med stöd: ${p.guided}`,
    `Varje elev genomför självständigt: ${p.independent}`
  ];
  return {
    id:`${prefix}-${String(index + 1).padStart(2,"0")}`, area, text, goal:p.goal,
    lesson:{title:p.title,duration:p.duration || "2 × 70 minuter",steps,check:p.check,delayedCheck:p.delayed},
    solMethods:methods, sources:[], prerequisites:p.pre, likelyDifficulty:p.difficulty,
    exampleOrModel:steps[1], guidedPractice:steps[2], independentPractice:steps[3],
    contrastOrVariation:p.contrast,
    decisionRule:`Om fler än 25 procent visar att ${p.signal}, modellerar läraren den kritiska skillnaden igen med ett nytt exempel. Annars går gruppen vidare till överföringsuppgiften.`,
    transferTask:p.transfer,
    methodRationale:methods.map(method => ({method,rationale:rationale[method] || "stödjer bearbetning och återkoppling för denna innehållspunkt"})),
    evidenceSources, reviewStatus:"Redaktionellt SoL-förslag - ej ämneslärargranskat"
  };
}

const T = (area,text,title,goal,recall,model,guided,independent,check,delayed,pre,difficulty,signal,contrast,transfer,methods) => ({area,text,p:{title,goal,recall,model,guided,independent,check,delayed,pre,difficulty,signal,contrast,transfer,methods}});

const teknik = [
T("Tekniska processer och system","Tillämpning av teknikutvecklingsprocessen inom något teknikområde.","Designsprint för en bullersnål studieplats","Eleven kan driva en iterativ teknikutvecklingsprocess och använda testdata för nästa beslut.","rita processens steg och markera var återkoppling sker","ett ljuddämpande bordsavskärmarsystem går från mätbart behov till omarbetad prototyp","testa två materialprover och revidera en kravpunkt utifrån mätningen","lämna en processlogg där ett misslyckat test leder till en motiverad iteration","Peka ut vilket testresultat som bör ändra konstruktionen och varför.","Efter en vecka planeras processen för ett ljusstyrningsproblem utan processmall.",["kravspecifikation","prototyp","testkriterium"],"processen behandlas som en checklista trots att testresultat kräver omtag","eleven inte kan koppla ett testresultat till ett specifikt omtag","Jämför en plan som döljer omtag med en versionshistorik där testdata styr nästa steg.","Överför processen till utveckling av en digital bokningstjänst."),
T("Tekniska processer och system","Entreprenörskap och entreprenörskapets villkor i en innovativ och kreativ teknikutvecklingsprocess.","Från uppfinning till livskraftigt erbjudande","Eleven kan väga användarbehov, resurser, risk och värdeskapande i en teknisk affärsidé.","skriv skillnaden mellan uppfinning, innovation och affärsmodell","hur en reparerbar laddare prövas mot kundnytta, kostnad och immaterialrätt","granska tre antaganden i en enkel business-model-canvas och föreslå billiga tester","formulera ett värdeerbjudande och ett experiment som kan falsifiera dess viktigaste antagande","Vilket antagande är mest riskfyllt och vilket belägg behövs?","Eleverna återkallar beslutsramen när en ny cirkulär produktidé bedöms.",["behov","målgrupp","kostnad och intäkt"],"en kreativ idé antas automatiskt vara en genomförbar innovation","eleven endast beskriver produktens funktion och inte villkoren för införande","Jämför två lika originella idéer där bara den ena har belagt behov och realistiska resurser.","Bedöm en öppen källkodsbaserad tjänst med samma entreprenöriella ram."),
T("Problemlösning","Problemlösning och praktisk tillämpning inom något teknikområde, till exempel produktion, design eller informationsteknik.","Felsök produktionslinjen","Eleven kan avgränsa, diagnostisera och testa en teknisk lösning systematiskt.","lista stegen hypotes–test–data–beslut","hur ett intermittent sensorfel isoleras utan att alla komponenter byts samtidigt","använd ett felträd för att välja nästa mätning i en simulerad produktionscell","lösa ett nytt fel med begränsat antal tester och dokumentera varför varje test valdes","Välj nästa test som ger mest information, inte bara det enklaste testet.","Fyra dagar senare felsöks ett nätverksproblem med samma strategi.",["systemgräns","orsak och symptom","mätning"],"symptom åtgärdas på måfå utan att orsaken isoleras","eleven ändrar flera variabler samtidigt eller saknar hypotes","Jämför komponentbyte på chans med ett test som skiljer mellan två hypoteser.","Använd felsökningslogiken på en användbarhetsbrist i en app.",["Aktiv återkallning","Modellering","Felanalys","Överföring"]),
T("Problemlösning","Metodik och arbetsformer i projekt.","Projektets kritiska väg på klassrumsväggen","Eleven kan välja arbetsform, synliggöra beroenden och följa upp leveranser i ett teknikprojekt.","skilj aktivitet, leverans, milstolpe och beroende","hur en försening i komponentval påverkar CAD, inköp och prototyptest","bygga ett kanbanflöde och identifiera arbete som blockerar andra","planera en tvåveckors iteration med ansvar, acceptanskriterier och riskreserv","Vilken aktivitet måste prioriteras för att inte försena helheten?","Nästa projektstart börjar med en tom beroendekarta som minnestest.",["projektmål","roller","tidsuppskattning"],"en aktivitetslista förväxlas med en styrbar projektplan","eleven inte kan förklara beroenden eller acceptanskriterier","Jämför en full kalender med en kort plan som visar kritiska beroenden och färdigt-kriterier.","Byt från sekventiellt projekt till iterativ mjukvaruutveckling och motivera arbetsformen."),
T("Problemlösning","Tillämpning av programmering för problemlösning.","Styr växthuset med tillstånd och återkoppling","Eleven kan översätta ett tekniskt reglerproblem till algoritm, kod och testfall.","skriv pseudokod för ett villkor med hysteres","hur temperatur, börvärde och fläktläge bildar en tillståndsmaskin","spåra kod mot sensordata och hitta ett gränsfall som ger snabbt av/på-slag","implementera styrningen och bevisa funktionen med normala värden och gränsvärden","Förutsäg utdata för tre sensorvärden innan programmet körs.","Efter fem dagar ändras problemet till automatisk belysning med samma kontrollidé.",["variabel","villkor och loop","sensorvärde"],"kod skrivs före problemmodell och fungerar därför bara för testvärdet","eleven inte kan förutsäga kodens utdata eller ange ett gränsfall","Jämför en enkel tröskel med hysteres när mätvärdet varierar runt gränsen.","Överför algoritmen från simulering till en fysisk mikrokontroller.",["Genomarbetade exempel","Felanalys","Självförklaring","Överföring"]),
T("Problemlösning","Systematiskt kvalitetsarbete, däribland kvalitetssäkring, miljösäkring och riskanalys samt frågor om arbetsmiljö.","Kvalitetsrevision av skolans makerspace","Eleven kan skilja förebyggande kvalitetssäkring från slutkontroll och prioritera riskåtgärder.","definiera sannolikhet, konsekvens, rotorsak och kontrollpunkt","hur en borrstation analyseras med riskmatris, fem varför och kontrollplan","bedöma risker i ett stationsfoto och välja åtgärd enligt eliminera–minska–skydda","skapa en kvalitets- och miljöplan för en laserskärningsprocess","Vilken åtgärd angriper orsaken och hur verifieras effekten?","En månad senare görs en oanmäld minirevision med nya avvikelser.",["krav","mätosäkerhet","risk"],"slutkontroll ses som tillräcklig och riskpoäng ersätter analys av åtgärd","eleven föreslår mer försiktighet utan mätbar eller förebyggande kontroll","Jämför personlig skyddsutrustning med eliminering av faran vid källan.","Tillämpa kontrollplanen på kvalitet och integritet i en digital tjänst."),
T("Begrepp, teorier och modeller","Tillämpning av begrepp, teorier och modeller för att konstruera, dimensionera, beräkna och bedöma rimligheten i tekniska lösningar inom något teknikområde.","Dimensionera en gångbro av papper","Eleven kan använda en teknisk modell för dimensionering och kontrollera enheter, säkerhetsmarginal och rimlighet.","återkalla samband mellan last, spänning, tvärsnitt och säkerhetsfaktor","en balk dimensioneras från krav till valt tvärsnitt med enhets- och överslagskontroll","räkna på två balkprofiler och förklara varför lika materialmängd inte ger lika styvhet","dimensionera en pappersbro, förutsäga brottlast och jämföra med fysisk provning","Markera vilket antagande som mest påverkar säkerhetsmarginalen.","Senare dimensioneras ett hyllplan med andra enheter och lastfall.",["kraft och moment","enheter","materialegenskaper"],"formeln används korrekt men modellen, enheten eller säkerhetsmarginalen blir orimlig","eleven inte gör en oberoende rimlighetskontroll","Jämför två numeriskt snygga svar där ett bryter mot enhet eller realistisk storleksordning.","Använd samma kontrollkedja för elektrisk effekt och kabeldimensionering."),
T("Begrepp, teorier och modeller","Modellering och simulering inom något teknikområde med hjälp av relevanta metoder.","Kalibrera en digital tvilling av ett klassrum","Eleven kan bygga, kalibrera och avgränsa en simulering mot mätdata.","skriv skillnaden mellan parameter, indata, utdata och antagande","hur en enkel temperaturmodell justeras mot en mätserie utan att överanpassas","ändra en parameter i taget och tolka residualerna mellan modell och mätning","validera modellen på en ny dag och ange dess giltighetsområde","Vilken avvikelse visar modellbrist snarare än mätbrus?","Två veckor senare väljs modelltyp för ett batteris urladdning.",["funktioner","mätdata","systemgräns"],"simuleringens graf tas som verklighet och modellens antaganden blir osynliga","eleven inte kan ange vad modellen utelämnar eller hur den validerats","Jämför en modell som passar träningsdata perfekt med en enklare modell som fungerar på nya data.","Välj mellan fysisk prototyp och simulering för ett kostsamt krocktest."),
T("Teknik, människa och samhälle","Tekniska framsteg och teknikutveckling med fokus på framtidens teknik och en hållbar utveckling, till exempel cirkulär ekonomi och nya affärsmodeller.","Cirkulär omdesign av en mobiltelefon","Eleven kan föreslå en cirkulär lösning och analysera materialflöde, incitament och rekyleffekter.","rita skillnaden mellan linjärt och cirkulärt materialflöde","en telefon omdesignas för reparation, återtag och komponentåterbruk","kartlägga var värde och material förloras i en vald produktkedja","skapa en cirkulär affärsmodell och testa den mot ett oväntat användarbeteende","Vilken del av förslaget minskar faktiskt jungfruligt material per funktion?","Efter en vecka analyseras en tjänst där effektivisering kan skapa rekyleffekt.",["livscykel","resursflöde","affärsmodell"],"cirkulär ekonomi reduceras till återvinning utan livslängd, återbruk eller incitament","eleven inte följer ett faktiskt materialflöde genom systemet","Jämför återvinningsbar engångsprodukt med reparerbar produkt i ett återtagssystem.","Överför analysen till batterilagring eller delad mobilitet."),
T("Teknik, människa och samhälle","Värdering av tekniska lösningar utifrån olika aspekter, däribland genus, etik och hållbar utveckling.","Etisk prövning av ansiktsigenkänning","Eleven kan värdera en teknisk lösning med flera perspektiv, belägg och explicita målkonflikter.","skilj konsekvens, rättighet, fördelning och teknisk prestanda","hur ansiktsigenkänning i skolan bedöms för olika grupper och alternativa lösningar","använda en intressentmatris på tre införandescenarier med olika felrisk","skriva en villkorad rekommendation som anger vem som gynnas, riskerar skada och vilka belägg som saknas","Vilket nytt belägg skulle kunna ändra din rekommendation?","Senare prövas samma etiska ram på AI-baserad rekrytering.",["intressent","bias","hållbarhetens dimensioner"],"värderingen blir en personlig åsikt eller en enda totalpoäng som döljer fördelning","eleven inte skiljer fakta, värdering och berörd grupp","Jämför hög genomsnittlig träffsäkerhet med ojämn felrisk mellan grupper.","Värdera en energiteknik där klimatnytta står mot lokal påverkan."),
T("Teknik, människa och samhälle","Digitaliseringens betydelse för produktion, kommunikation och människans livsmiljö.","Ett paket genom den digitala fabriken","Eleven kan förklara hur data, automatisering och återkoppling förändrar arbete och systemrisker.","rita informationsflödet sensor–databas–beslut–maskin","hur ett kundköp påverkar lagerrobot, prognos, leverans och arbetsroll","spåra ett felaktigt datavärde genom en digital produktionskedja","analysera en vald digitalisering och föreslå både effektivitetsmått och skyddsräcke","Var i kedjan ger ett fel störst följdeffekt och varför?","Efter sex dagar jämförs fabriksfallet med digital vårdkommunikation.",["tekniskt system","dataflöde","automation"],"digitalisering beskrivs som att datorer införs, utan systemberoenden och förändrade roller","eleven bara listar för- och nackdelar utan orsakskedja","Jämför lokal automatisering med ett uppkopplat system som optimerar helheten men ökar beroenden.","Analysera hur samma teknik förändrar hemmiljö eller kollektivtrafik."),
T("Teknisk kommunikation","Kommunikation, dokumentation och presentation inom något teknikområde.","Beslutslogg som en annan ingenjör kan fortsätta","Eleven kan dokumentera krav, beslut, testdata och versioner så att arbetet kan granskas och reproduceras.","skriv vilka fyra spår som krävs från krav till verifiering","hur ett designbeslut länkas till testdata, ritningsversion och avvikelse","återskapa ett projektbeslut ur ofullständig respektive spårbar dokumentation","överlämna en teknisk lösning till en klasskamrat som ska genomföra nästa ändring utan muntlig hjälp","Kan mottagaren hitta varför lösningen ändrades och vilket krav som verifierades?","Nästa projekt granskas med ett oanmält versions- och spårbarhetstest.",["krav","mottagare","versionshantering"],"dokumentationen blir en kronologisk berättelse men saknar spårbarhet","eleven inte kan länka beslut till krav och data","Jämför en snygg slutrapport med en kort beslutslogg som gör en ändring reproducerbar.","Skriv om samma underlag för kund, tillverkare och tillsynsansvarig."),
T("Teknisk kommunikation","Tolkning och framställning av digitala ritningar och modeller.","CAD-stafetten: bygg från någon annans ritning","Eleven kan skapa och tolka en digital modell med rätt vyer, mått, toleranser och revisionsinformation.","skissa vad som krävs för att entydigt beskriva en detalj","hur en 3D-modell härleds till vyer och måttsätts utifrån funktion, inte utseende","identifiera tvetydigheter i tre ritningar och korrigera dem före modellering","modellera en kopplingsdetalj som en annan elev tillverkar utan extra frågor","Vilket mått eller vilken tolerans avgör om delarna faktiskt passar?","Efter en vecka tolkas en ritning med annan projektion och en avsiktlig revisionskonflikt.",["projektion","måttsättning","tolerans"],"3D-modellen ser riktig ut men saknar tillverkningskritisk information","eleven måttsätter dubbelt eller utelämnar funktionella toleranser","Jämför fotorealistisk rendering med enkel arbetsritning för tillverkning.","Välj representationspaket för montör, beställare och reservdelstillverkare.")
];

const matematik = [
T("Aritmetik, algebra och funktioner","Begreppet linjärt ekvationssystem. Metoder för att lösa linjära ekvationssystem.","Tre metoder, samma skärningspunkt","Eleven kan välja och kontrollera grafisk metod, substitution eller elimination.","tolka en lösning som ett ordnat talpar som uppfyller båda ekvationerna","hur två mobilabonnemang blir ett system och löses med elimination","sortera system efter vilken lösningsmetod som ger minst arbete","lösa ett nytt kostnadsproblem med vald metod och kontroll genom insättning","Förklara varför din metod är effektiv för just detta system.","Efter fyra dagar blandas system med en, ingen och oändligt många lösningar.",["linjär funktion","ekvationslösning","koordinatsystem"],"eleven följer en metod men tappar innebörden av den gemensamma lösningen","eleven bara kontrollerar en av ekvationerna","Jämför två skärande, parallella och sammanfallande linjer algebraiskt och grafiskt.","Formulera ett eget system från blandning eller kraftjämvikt."),
T("Aritmetik, algebra och funktioner","Begreppet logaritm. Motivering och hantering av räkneregler för logaritmer. Metoder för att lösa exponentialekvationer.","Logaritmen som frågan efter exponenten","Eleven kan förklara logaritmbegreppet, motivera regler och lösa exponentialekvationer.","översätt mellan 2³=8 och log₂8=3","hur produktregeln följer av potensregeln och används i en pH-liknande skala","para ihop exponentformer, logaritmformer och typiska fel","lösa en tillväxtekvation och kontrollera svaret i ursprungsekvationen","Härled en logaritmregel i stället för att bara citera den.","En vecka senare återkallas reglerna i blandade ekvationer utan formelblad.",["potensregler","invers funktion","exponentialfunktion"],"logaritmregler övergeneraliseras till summor","eleven skriver log(a+b)=log a+log b","Jämför log(ab) med log(a+b) genom numeriska motexempel.","Bestäm halveringstid eller ljudnivå i en ny naturvetenskaplig kontext."),
T("Aritmetik, algebra och funktioner","Likheter och skillnader mellan exponential- och potensekvationer.","Var sitter variabeln? Modellkliniken","Eleven kan urskilja potens- och exponentialstruktur och välja lösningsmetod.","klassificera x³=20 och 3ˣ=20 utan att lösa","hur variabelns position avgör rot- respektive logaritmmetod","blanda ekvationskort och motivera metod före beräkning","lösa två ytlika ekvationer och skriva beslutsregel","Välj metod och ange den strukturella ledtråden.","Efter fem dagar infogas linjära och andragradsekvationer i samma sortering.",["potensfunktion","exponentialfunktion","rot och logaritm"],"yttre symboler styr metodvalet i stället för variabelns roll","eleven väljer logaritm när variabeln är bas","Jämför 2ˣ=16, x²=16 och 2x=16 sida vid sida.","Klassificera och lös modeller för area respektive befolkningstillväxt.",["Aktiv återkallning","Kontrasterande exempel","Blandad övning","Självförklaring"]),
T("Aritmetik, algebra och funktioner","Motivering och hantering av konjugatregeln och kvadreringsreglerna.","Algebraiska identiteter med areapussel","Eleven kan motivera och använda kvadrerings- och konjugatreglerna åt båda hållen.","rita (a+b)² som en kvadrat med delareor","hur areamodellen ger mittentermen 2ab","bygga och felsöka pussel för (a-b)² och (a+b)(a-b)","välja regel för utveckling och faktorisering av blandade uttryck","Varifrån kommer varje term i identiteten?","Reglerna återkallas senare vid lösning av andragradsekvationer.",["distributiva lagen","area","negativa tal"],"mittentermen eller tecknet försvinner när regeln memoreras utan struktur","eleven inte kan förklara 2ab eller minustecknet","Jämför (a-b)² med a²-b² genom expansion och numeriskt test.","Använd identiteterna för huvudräkning och förenkling av en geometrisk formel."),
T("Aritmetik, algebra och funktioner","Begreppet andragradsfunktion och egenskaper hos andragradsfunktioner, däribland symmetrilinje, extrempunkt och nollställen.","Parabelns fingeravtryck","Eleven kan koppla funktionsform till grafens nollställen, symmetri och extrempunkt.","markera nollställen och extrempunkt i en omärkt parabel","hur faktorform, utvecklad form och kvadratkompletterad form avslöjar olika egenskaper","matcha grafer med tre algebraiska former och motivera varje matchning","konstruera en andragradsfunktion med givna geometriska villkor","Vilken representation ger snabbast den efterfrågade egenskapen?","Efter en vecka analyseras en ny parabel utan grafverktyg.",["funktionsbegrepp","faktorisering","koordinatsystem"],"egenskaper avläses separat utan koppling till funktionens algebraiska form","eleven tror att extrempunktens x-värde alltid är ett nollställe","Jämför parabler med samma nollställen men olika ledande koefficient.","Modellera höjden hos ett kast och tolka relevanta delar av grafen."),
T("Aritmetik, algebra och funktioner","Metoder för att lösa andragradsekvationer.","Metodval före pq-formel","Eleven kan välja mellan faktorisering, rotmetod, graf och generell formel samt kontrollera lösningar.","klassificera ekvationer efter synlig struktur","hur x²=25, x²+5x=0 och x²+5x+4=0 löses med olika ekonomiska metoder","lösa en trappa av ekvationer där stödet för metodval minskar","skriva en lösningsguide och använda den på en ny blandad serie","Motivera metodvalet innan första beräkningen.","Fyra dagar senare blandas andragrads- och rotekvationer med extrarötter.",["nollprodukt","kvadreringsregler","funktionsgraf"],"pq-formeln används mekaniskt även när struktur och villkor förbises","eleven inte kontrollerar båda rötterna eller väljer onödigt tung metod","Jämför en faktoriserbar ekvation med en snarlik som kräver generell metod.","Lös ett optimeringsproblem och tolka vilken rot som är meningsfull."),
T("Aritmetik, algebra och funktioner","Metoder för att lösa rotekvationer.","Jakten på extraroten","Eleven kan isolera rotuttryck, ange villkor och pröva kandidatlösningar.","ange definitionsvillkor för tre rotuttryck","hur kvadrering kan skapa en lösning som inte uppfyller ursprungsekvationen","spåra två lösningar där bara en klarar kontrollen","lösa en rotekvation och dokumentera villkor, transformation och slutkontroll","Vilket steg kan skapa extralösning och hur upptäcks den?","Efter sex dagar blandas rotekvationer med vanliga andragradsekvationer.",["kvadratrot","ekvivalens","andragradsekvation"],"kvadrering behandlas som ekvivalens och extralösningar behålls","eleven inte prövar kandidaten i ursprungsekvationen","Jämför ett ekvivalent algebrasteg med kvadrering som bara ger implikation.","Formulera och lös en avståndsekvation i koordinatsystem."),
T("Statistik","Lägesmått och spridningsmått, däribland percentiler och standardavvikelse, samt digitala metoder för att bestämma dessa.","Samma medelvärde, helt olika klassrum","Eleven kan välja och tolka läges- och spridningsmått för en datamängd.","skapa två små datamängder med samma medelvärde","hur median, kvartiler och standardavvikelse svarar på extremvärden","jämföra tre elevresultatfördelningar i kalkylverktyg","skriva en databerättelse som använder både centrum och spridning utan att överdriva","Vilket mått förändras mest när extremvärdet läggs till och varför?","En vecka senare väljs mått för löner, sensordata och väntetider.",["medelvärde","median","datamängd"],"ett enda lägesmått används som fullständig beskrivning","eleven jämför grupper utan spridningsmått eller påverkas omotiverat av extremvärden","Jämför två datamängder med samma medelvärde men olika standardavvikelse.","Välj mått för kvalitetskontroll av tillverkade komponenter."),
T("Statistik","Begreppet normalfördelning och egenskaper hos normalfördelat material. Digitala metoder för att göra beräkningar på normalfördelat material.","Normalfördelning eller förklädd skevhet?","Eleven kan känna igen, standardisera och beräkna andelar i en normalmodell samt granska modellvalet.","skissa vad medelvärde och standardavvikelse gör med en normalkurva","hur ett mätvärde omvandlas till z-värde och area","matcha histogram med rimliga och orimliga normalmodeller","beräkna en toleransandel digitalt och ange varför modellen kan fallera","Är normalmodellen rimlig innan du använder den? Ge två belägg.","Efter en vecka jämförs normaldata med tydligt snedfördelade väntetider.",["standardavvikelse","area och andel","symmetri"],"klockform antas utan kontroll och digital sannolikhet saknar tolkning","eleven använder normalmodell på skevt eller begränsat material","Jämför symmetrisk mätvariation med en väntetidsfördelning med lång svans.","Beräkna kassationsrisk för en komponent med givna toleransgränser."),
T("Statistik","Begreppen regressionsanalys och korrelationskoefficient. Digitala metoder för regressionsanalys.","Regression utan orsaksmagi","Eleven kan skapa och tolka en regressionsmodell samt skilja samband, prognos och orsak.","förutsäg tecken och ungefärlig styrka för tre punktmoln","hur digital regression ger modell, residualer och korrelationskoefficient","jämföra ett starkt icke-linjärt samband med ett svagt linjärt samband","analysera en öppen datamängd och skriva en begränsad prognos","Vilket påstående stöds av data: samband, prognos eller orsak?","Senare granskas ett mediepåstående med dold tredje variabel.",["linjär funktion","punktdiagram","spridning"],"hög korrelation tolkas som kausalitet eller god modell utan residualkontroll","eleven skriver att x orsakar y enbart utifrån r-värdet","Jämför hög korrelation med systematiska residualer och lägre korrelation med användbar lokal modell.","Undersök energiåtgång mot temperatur och diskutera störvariabler."),
T("Logik och geometri","Begreppen implikation och ekvivalens.","Enkelriktade och dubbelriktade matematiska dörrar","Eleven kan skilja implikation från ekvivalens och identifiera reversibla lösningssteg.","avgör om fyra vardagliga om–så-påståenden kan vändas","hur kvadrering och addition påverkar lösningsmängden olika","märka pilarna i ett lösningsbevis som enkel- eller dubbelriktade","reparera ett resonemang där omvändningen är falsk","Kan steget vändas utan nya lösningar eller förlorade fall?","Efter fyra dagar analyseras en rotekvation med samma logiska språk.",["villkor","mängd","ekvationslösning"],"en sann implikation antas automatiskt vara sann åt båda håll","eleven vänder ett villkor utan motexempel eller kontroll","Jämför 'delbart med 4 ⇒ jämnt' med dess falska omvändning.","Granska villkor i ett programmerat beslutsträd."),
T("Logik och geometri","Begreppen definition, sats och bevis.","Bygg ett bevis av påståendekort","Eleven kan skilja definition, sats och exempel samt bygga ett giltigt deduktivt resonemang.","sortera meningar som definition, antagande, sats eller exempel","hur ett kort paritetsbevis byggs från definition till slutsats","ordna blandade bevisrader och markera motiveringen för varje steg","skriva ett eget bevis och låta en kamrat försöka hitta ett logiskt glapp","Vilket steg saknar stöd av definition, antagande eller tidigare sats?","En vecka senare rekonstrueras bevisets struktur ur minnet med nytt innehåll.",["logisk följd","algebra","motexempel"],"många kontrollerade exempel uppfattas som ett allmänt bevis","eleven hänvisar till mönster men inte visar varför alla fall omfattas","Jämför tio korrekta numeriska exempel med ett symboliskt bevis och ett enda motexempel.","Bevisa en enkel egenskap hos summan av två udda tal."),
T("Logik och geometri","Motivering och användning av enklare geometriska satser om vinklar och likformighet samt Pythagoras sats med exempel som omfattar beräkningar i koordinatsystem.","Geometriskt detektivarbete i koordinatnät","Eleven kan välja och motivera geometrisk sats i en flerstegsfigur.","återkalla villkoren för likformighet och Pythagoras sats","hur en okänd höjd bestäms via parallellitet, vinklar och likformighet","markera givna fakta respektive härledda fakta i en koordinatfigur","lösa ett mätproblem och skriva vilken sats som legitimerar varje steg","Vilket villkor måste visas innan satsen får användas?","Senare blandas figurer där likformighet ser möjlig ut men villkoren saknas.",["vinklar","proportion","avstånd"],"en sats väljs efter figurens utseende utan att villkoren verifieras","eleven använder Pythagoras utan rät vinkel eller likformighet utan vinkelvillkor","Jämför två nästan identiska triangelfigurer där endast en uppfyller satsens villkor.","Bestäm en otillgänglig sträcka från koordinater eller skuggmätning."),
T("Digitala verktyg","Användning av digitala verktyg för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning och problemlösning.","Digitalt svar under korsförhör","Eleven kan välja digitalt verktyg, ställa in det korrekt och verifiera resultatets giltighet.","lista tre felkällor i graffönster, syntax och avrundning","hur samma ekvation löses symboliskt, grafiskt och numeriskt med oberoende kontroll","diagnostisera skärmbilder som döljer rötter eller visar falsk precision","välja verktyg för tre problem och dokumentera inställning samt rimlighetskontroll","Vilken oberoende kontroll gör att resultatet blir trovärdigt?","Vid nästa arbetsområde ges ett avsiktligt missvisande digitalt resultat.",["ekvationslösning","graf","avrundning"],"verktygets utdata accepteras utan kontroll av domän, fönster eller precision","eleven inte kan återskapa eller rimlighetsbedöma svaret","Jämför korrekt algebra med ett graffönster som bara visar en av två lösningar.","Välj verktyg för en teknisk modell med mätdata och argumentera för valet."),
T("Digitala verktyg","Exempel på hur programmering kan användas som verktyg vid problemlösning, databearbetning eller tillämpning av numeriska metoder.","Newtoniteration rad för rad","Eleven kan koppla en numerisk algoritm i kod till matematisk idé, stoppvillkor och fel.","spåra tre varv i en enkel iterationsloop för hand","hur Newtons metod närmar sig en rot och kan misslyckas med olämpligt startvärde","fylla i saknade kodrader och förutsäga konvergens innan körning","modifiera programmet för tolerans, maxantal steg och loggning av fel","Vad betyder varje variabel matematiskt och när ska programmet stanna?","En vecka senare används samma kodläsning på databearbetning.",["funktion","loop","felmarginal"],"fungerande kod förväxlas med förstådd och tillförlitlig numerisk metod","eleven inte kan förutsäga iteration eller motivera stoppvillkor","Jämför två program som ger samma svar men olika robusthet vid dåliga startvärden.","Använd iteration för att uppskatta en lösning i en ny fysikalisk modell."),
T("Problemlösning och tillämpningsområden","Problemlösning med särskild utgångspunkt i utbildningens karaktär och samhällsliv, däribland frågeställningar som berör hållbar utveckling och hur matematik kan användas för kritisk granskning av fakta och påståenden.","Klimatpåståendet på provbänken","Eleven kan formulera, beräkna och kritiskt granska ett kvantitativt samhällspåstående.","identifiera basvärde, enhet och tidsperiod i tre rubriker","hur ett påstående om energibesparing bryts ned i antaganden och storleksordningar","faktagranska en infographic genom omräkning per person och per år","skriva en transparent kontroll med källa, antagande, beräkning och osäkerhet","Vilken nämnare eller jämförelse saknas för att påståendet ska bli meningsfullt?","Efter en vecka granskas ett nytt påstående utan färdig analysmall.",["procent","enheter","storleksordning"],"korrekt siffra blir missvisande när bas, nämnare eller tidsskala saknas","eleven återger procenttal utan jämförelsebas","Jämför total utsläppsminskning med minskning per producerad enhet.","Granska ett tekniskt företags hållbarhetspåstående."),
T("Problemlösning och tillämpningsområden","Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.","Modellverkstad för elcykelns räckvidd","Eleven kan formulera, anpassa, testa och begränsa en matematisk modell.","lista variabler och antaganden som påverkar räckvidd","hur en enkel energimodell byggs, dimensionskontrolleras och jämförs med data","justera parametrar mot två resor och analysera residualer","förutsäga en tredje resa och skriva modellens giltighetsområde","Vilket antagande orsakar störst prognosfel och hur kan det testas?","Två veckor senare kritiseras en modell med extrapolation utanför data.",["funktioner","enheter","data"],"en välanpassad modell behandlas som sann utanför sitt kalibrerade område","eleven inte anger antaganden eller giltighetsintervall","Jämför två modeller som passar befintliga data men ger olika långsiktig prognos.","Bygg en modell för uppvärmning eller kostnad i en annan kurs."),
T("Problemlösning och tillämpningsområden","Orientering om något ur matematikens historia, till exempel hur ett matematiskt begrepp utvecklats, matematikens roll i något historiskt skeende, en betydande person inom matematiken eller ett historiskt matematiskt problem.","Nollans väg mellan problem, kultur och notation","Eleven kan förklara hur matematiska behov, representationer och spridning samverkade historiskt.","ordna fyra representationsformer för tal på en preliminär tidslinje","hur positionssystem och nolla förändrar både beräkning och kommunikation","jämföra beräkning med romerska siffror och positionssystem samt tolka källfragment","skapa en belagd orsak–förändring–konsekvenskedja för ett annat begrepp","Hur förändrade notationen vad människor kunde göra matematiskt?","När begreppet används senare återkallas dess historiska problem och genombrott.",["positionssystem","tidslinje","historisk källa"],"historien reduceras till namn och år utan koppling till matematiskt problem","eleven inte kan förklara vad den nya representationen möjliggjorde","Jämför samma beräkning före och efter en notationell innovation.","Undersök logaritmers eller negativa tals utveckling med samma analysram.")
];

const svenska = [
T("Muntlig framställning","Muntlig framställning av utredande och argumenterande slag i och inför grupp. Tillämpning av den retoriska arbetsprocessen för att planera och genomföra muntliga utredande och argumenterande framställningar i olika sammanhang, för olika syften och för olika mottagare. Retoriska verkningsmedel.","Retoriklaboratoriet: samma tes, tre auditorier","Eleven kan genomföra den retoriska arbetsprocessen och anpassa argument och verkningsmedel till situationen.","skriv arbetsprocessens steg och ett syfte med varje","hur en tes om mobilförbud förändras för elevråd, vårdnadshavare och rektor","omarbeta inledning, belägg och avslutning för ett tilldelat auditorium","framföra ett treminuterstal och lämna en kommenterad dispositionsplan","Vilket retoriskt val är tydligast knutet till mottagaren?","Efter en vecka hålls ett nytt kort utredande anförande utan manusmall.",["tes","disposition","ethos, logos och pathos"],"retoriska figurer läggs på som pynt utan koppling till syfte och mottagare","eleven inte kan motivera ett språk- eller beläggsval utifrån situationen","Jämför samma argument med anekdot respektive statistik inför två olika auditorier.","Anpassa anförandet till en skeptisk fackpublik."),
T("Skriftlig framställning","Skriftlig framställning av argumenterande och utredande texter och kreativt skrivande.","Tre skrivuppdrag från samma kärnfråga","Eleven kan välja textstruktur och språkhandling för argumentation, utredning och gestaltning.","sortera stycken efter om de driver tes, utreder perspektiv eller gestaltar","hur frågan om övervakning öppnas i tre genrer med olika kontrakt","skriva samma centrala konflikt som tesstycke, utredande jämförelse och scen","utveckla en av texterna och kommentera fem genretypiska beslut","Vilka textdrag visar läsaren vilket uppdrag texten fullgör?","Senare byter eleven genre på ett nytt ämne utan stödlista.",["syfte","stycke","berättarperspektiv"],"ämnet snarare än kommunikationsuppgiften styr struktur och språk","eleven blandar tesdrivande och neutralt utredande språk omedvetet","Jämför en balanserad utredning med ett argumenterande stycke om samma fråga.","Omvandla ett personporträtt till en kreativ scen ur en annan synvinkel."),
T("Textstruktur och språkriktighet","Struktur och språkliga drag i argumenterande och utredande texter. Skriftspråkets normer för språkriktighet och vilka språkliga egenskaper som gör att en text fungerar väl i sitt sammanhang. Användning av digitala verktyg för textbearbetning samt för respons på texter. Citat- och referatteknik.","Textrevision i fyra separata linser","Eleven kan revidera disposition, samband, språkriktighet och källintegration med avsikt.","namnge skillnaden mellan global och lokal revision","hur ett svagt utredande stycke förbättras i ordningen funktion–struktur–språk–referens","ge kamratrespons med en lins i taget och belägga kommentaren i texten","bearbeta egen versionshistorik och motivera fyra ändringar","Förbättrade ändringen textens funktion eller bara dess yta? Visa var.","Efter en vecka kallrevideras ett nytt stycke utan checklista.",["tes och frågeställning","textbindning","referatmarkör"],"stavningskontroll och småspråk ersätter revision av resonemang och struktur","eleven börjar korrekturläsa innan textens funktion och disposition fungerar","Jämför en språkligt korrekt men ologisk text med en strukturellt tydlig råversion.","Revidera en laborationsdiskussion med samma fyra linser."),
T("Sakprosa","Läsning av och samtal om sakprosa. Produktion av texter som anknyter till läst sakprosa.","Sakprosaseminarium med beläggskarta","Eleven kan rekonstruera en sakprosatexts resonemang och använda det självständigt i en ny text.","förutsäg tes och texttyp från paratext","hur tes, delpåstående, belägg och reservation märks ut i en debattartikel","bygga en gemensam argumentkarta och lösa oenighet med exakta textställen","skriva en replik eller syntes som korrekt återger och prövar resonemanget","Kan varje tolkning och invändning spåras till textbelägg?","Fyra dagar senare återges resonemanget ur minnet innan texten öppnas igen.",["huvudidé","belägg","referat"],"läsningen stannar vid innehållsreferat och den egna texten anknyter bara tematiskt","eleven inte kan återge relationen mellan påstående och belägg","Jämför en tematisk kommentar med en replik som faktiskt besvarar författarens resonemang.","Använd läsmodellen på en populärvetenskaplig text om hälsa eller miljö."),
T("Informationssökning och källkritik","Informationssökning och värdering av information från olika typer av texter. Sammanfattning och kritisk läsning av texter från olika typer av källor.","Källkedjan bakom ett viralt påstående","Eleven kan söka lateralt, spåra ett påstående till ursprung och göra en källmedveten syntes.","skilj primärkälla, rapportering, kommentar och återpublicering","hur en viral statistikgraf spåras bakåt genom länkar till ursprunglig rapport","kartlägga tre källors beroenden och jämföra vad de faktiskt belägger","skriva en sammanfattning som markerar ursprung, osäkerhet och källornas relation","Är detta tre oberoende belägg eller tre återgivningar av samma källa?","En vecka senare granskas en ny källa utan färdig källmatris.",["avsändare","belägg","referatteknik"],"antal träffar eller professionell form förväxlas med oberoende belägg","eleven räknar återpubliceringar som flera källor","Jämför tre sajter som citerar samma rapport med två verkligt oberoende datakällor.","Spåra ett viralt hälsopåstående till rapport, statistik eller originalstudie."),
T("Skönlitteratur","Läsning av, samtal om och analys av samtida och äldre skönlitterära texter ur genrerna epik, lyrik och dramatik från Sverige och olika delar av världen, författade av såväl kvinnor som män. Dansk och norsk skönlitteratur, delvis på originalspråk.","Nordisk närläsning över tid och genre","Eleven kan analysera hur genre, tid, plats och språklig närhet formar en litterär text.","återkalla genrespecifika analysfrågor för epik, lyrik och dramatik","hur ett svenskt och ett norskt utdrag närläses utan att språkliga olikheter blir hela analysen","jämföra motiv och gestaltning i ett äldre drama och en samtida dikt från olika delar av världen","skriva en jämförande analys med två textbelägg från varje verk","Vilken skillnad kan beläggas i texten och vilken förklaring är bara en hypotes?","Senare möter eleverna ett kort danskt originalutdrag utan ordlista först.",["genre","motiv","textbelägg"],"kontextetiketter ersätter analys av hur texten faktiskt är gjord","eleven förklarar allt med epok eller land utan närläsning","Jämför två verk med samma motiv men olika genre, tid och berättarsituation.","Använd jämförelseramen på ett verk från en hittills obekant litterär tradition."),
T("Litteraturhistoria","Fördjupning i några litterära epoker samt skönlitteraturens relation till förhållanden och idéströmningar i samhället, historiskt och i nutid. Några tongivande författare från olika tider och från olika delar av världen.","Epoken som konflikt, inte faktalista","Eleven kan förklara ömsesidiga samband mellan litterära former, idéströmningar och samhällsvillkor.","placera kända epoker och idéer på en tom tidslinje","hur romantikens naturmotiv läses både som form och reaktion utan enkel kausalitet","bygga ett nätverk mellan utdrag, idé, institution, publik och historisk förändring","placera ett okänt utdrag med belägg, alternativ hypotes och uttryckt osäkerhet","Vilket textdrag stöder epokplaceringen och vad talar emot?","Varannan vecka återbyggs den kumulativa tidslinjen ur minnet.",["epok","idéströmning","historisk kontext"],"epoker memoreras som homogena paket och samhälle antas direkt orsaka textdrag","eleven bara namnger tidstypiska drag utan belägg eller konkurrerande förklaring","Jämför två samtida författare som reagerar olika på samma samhällsvillkor.","Koppla en nutida dystopi till äldre idéströmning utan att kalla den samma epok."),
T("Litterär analys","Skönlitterära verkningsmedel. Centrala litteraturvetenskapliga begrepp och deras användning.","Verkningsmedlets orsakskedja","Eleven kan använda litteraturvetenskapliga begrepp för att förklara hur textval skapar effekt och tolkningsmöjlighet.","matcha begrepp med korta exakta exempel","hur fri indirekt diskurs förändrar avstånd, kunskap och sympati i ett stycke","skriva kedjorna textdrag–begrepp–lokal effekt–tolkning för olika utdrag","göra en närläsning som prövar två möjliga effekter av samma verkningsmedel","Vilket ord eller vilken struktur i texten bär din analys?","Fem dagar senare analyseras samma begrepp i annan genre.",["berättare","bildspråk","komposition"],"begrepp prickas av utan förklaring av funktion eller tolkningsvärde","eleven namnger metafor eller perspektiv men inte visar effekt","Jämför samma händelse med intern respektive extern fokalisering.","Använd analyskedjan på filmens ljud eller bild och jämför med litterär text."),
T("Språkets uppbyggnad","Det svenska språkets grammatik, däribland hur ord, fraser och satser samspelar i språket. Analys av det svenska språkets uppbyggnad i olika typer av texter.","Grammatik som textens maskineri","Eleven kan analysera hur ord, fraser och satser samspelar och använda analysen för att förändra stil och tydlighet.","bygga en sats av flyttbara frasbrickor och markera fundament","hur nominalisering och bisats påverkar informationstäthet i myndighetstext","transformera samma innehåll mellan talspråksnära, journalistisk och akademisk syntax","revidera ett eget stycke och förklara förändringen med grammatiska begrepp","Hur ändrades informationsflöde och läsarens belastning när satsen byggdes om?","Senare återkommer begreppen i autentisk textrespons utan särskild grammatikrubrik.",["ordklass","fras","huvud- och bisats"],"grammatik reduceras till etiketter och kopplas inte till betydelse eller textfunktion","eleven kan identifiera led men inte använda analysen för ett medvetet textval","Jämför två grammatiskt korrekta meningar med olika fundament och informationsstruktur.","Analysera och förenkla syntaxen i en myndighetstext."),
T("Språkförhållanden i Norden","Språk och språkanvändning med särskild betoning på språkförhållanden i Sverige och övriga Norden. Svensk språklagstiftning, däribland hur svenskan, den språkliga mångfalden i Sverige och den enskildes tillgång till språk kan värnas samt de nationella minoritetsspråkens och teckenspråkets ställning. Flerspråkighet och dess betydelse för individ och samhälle.","Språkråd för en flerspråkig kommun","Eleven kan använda språklagstiftning och språkvetenskapliga perspektiv för att analysera ett autentiskt språkpolitiskt beslut.","skilj huvudspråk, minoritetsspråk, modersmål och teckenspråk","hur ett kommunalt informationsärende prövas mot tillgång, rättighet, begriplighet och resurser","inta roller som minoritetsspråkstalare, myndighet och nyanländ medborgare och granska samma förslag","skriva ett språkråd med lagstöd, konsekvensanalys och bemötande av målkonflikt","Vilken rättighet eller samhällsfunktion stöder rekommendationen?","Efter en vecka analyseras ett nordiskt språkval i digital offentlig service.",["språklig variation","rättighet","flerspråkighet"],"språkpolitik blir allmänna åsikter och flerspråkighet värderas utan juridisk eller samhällelig precision","eleven inte skiljer individens språkbruk från institutionens skyldigheter","Jämför svenskans ställning som huvudspråk med nationella minoritetsspråks särskilda skydd.","Utforma en språkpolicy för en nordisk skolapp." )
];

function addLevel(subjectId, spec, entries) {
  const subject = data.subjects.find(s => s.id === subjectId);
  if (!subject) throw new Error(`Ämnet ${subjectId} saknas`);
  const centralContent = entries.map((entry,index) => item(spec.prefix,index,entry.area,entry.text,entry.p));
  const level = {...spec, centralContent};
  delete level.prefix;
  subject.levels = subject.levels.filter(existing => existing.id !== level.id);
  subject.levels.push(level);
}

addLevel("teknik",{prefix:"teki2",id:"teki-2",name:"Nivå 2",levelCode:"TEKI2000X",points:100,status:"Komplett redaktionellt utkast",sourceUrl:"https://syllabuswebb.skolverket.se/syllabuscw/jsp/subject.htm?subjectCode=TEKI&tos=gy"},teknik);
addLevel("matematik",{prefix:"mate2c",id:"mate-2c",name:"Nivå 2c",levelCode:"MATE2C00X",points:100,status:"Komplett redaktionellt utkast",sourceUrl:"https://syllabuswebb.skolverket.se/syllabuscw/jsp/subject.htm?subjectCode=MATE&tos=gy"},matematik);
addLevel("svenska",{prefix:"sven2",id:"sven-2",name:"Nivå 2",levelCode:"SVEN2000X",points:100,status:"Komplett redaktionellt utkast",sourceUrl:"https://syllabuswebb.skolverket.se/syllabuscw/jsp/subject.htm?subjectCode=SVEN&tos=gy"},svenska);

data.metadata.updated = new Date().toISOString().slice(0,10);
for (const subject of data.subjects) for (const level of subject.levels) for (const entry of level.centralContent) applyClassification(entry);
for (const subject of data.subjects) for (const level of subject.levels) for (const entry of level.centralContent) applyPlanningStructure(subject, level, entry);
fs.writeFileSync(dataPath, `${JSON.stringify(data,null,2)}\n`);
console.log("Lade till Teknik 2, Matematik 2c och Svenska 2 med 41 unika planeringsidéer.");
