const C = {
  1: "Kapitel 1 – prestation i stunden, varaktigt lärande och fördröjd kontroll",
  2: "Kapitel 2 – mål, hinder, val, sortering och kontroll",
  3: "Kapitel 3 – kognitiv belastning (<em>cognitive load</em>) och segmentering",
  4: "Kapitel 4 – minnesåterkallning (<em>retrieval practice</em>)",
  5: "Kapitel 5 – utspridd övning (<em>spacing</em>), blandad övning (<em>interleaving</em>) och variation",
  6: "Kapitel 6 – förkunskaper (<em>prior knowledge</em>), scheman och begreppsundervisning",
  7: "Kapitel 7 – genomarbetade exempel (<em>worked examples</em>), modellering (<em>modeling</em>) och avvecklat stöd (<em>fading</em>)",
  8: "Kapitel 8 – samordning av bild och text samt signalering (<em>signaling</em>)",
  9: "Kapitel 9 – frågor, återkoppling (<em>feedback</em>) och kontroll av förståelse (<em>check for understanding</em>)",
  10: "Kapitel 10 – belägg, alternativa förklaringar och gränsvillkor (<em>boundary conditions</em>)",
};

function p(problem, chapters, lessonSequence, check, nextStep, delayedCheck) {
  return {
    problem,
    chapterLinks: chapters.map((chapter) => C[chapter]),
    lessonSequence,
    check,
    nextStep,
    delayedCheck,
  };
}

module.exports = {
  "svenska-f-3-1": p(
    "Eleverna kan peka på rätt bild när ordet sägs men kan inte själva förklara orden bo, skydd och föda efter läsningen.",
    [6, 4, 9, 1],
    [
      "Välj orden bo, skydd och föda ur den faktatext som klassen ska läsa. Visa ett fotografi och ett tydligt icke-exempel till varje ord.",
      "Läs det första stycket högt. Stanna där ett målord förekommer och modellera en förklaring: ”Ett bo är platsen där djuret vilar eller har ungar; den här stenen är ett skydd men inte ett bo.”",
      "Dölj orden. Låt alla elever säga eller rita vad ett av orden betyder och använda det om ett nytt djur, exempelvis igelkotten.",
      "Läs resten av texten och låt eleverna markera vilket av de tre orden som hjälper dem att förstå varje avsnitt.",
    ],
    "Visa tre nya djurbilder. Be varje elev välja ett målord och säga en mening som visar ordets betydelse; ett korrekt ord utan rimlig förklaring räknas inte som full förståelse.",
    "Om flera elever blandar ihop bo och skydd, visa ett fågelbo, en grotta och en buske och fråga vad som avgör kategorin. Om de skiljer orden säkert, låt dem använda två ord i samma förklaring.",
    "Två dagar senare får eleverna utan bilder förklara orden och använda ett av dem om ett djur som inte fanns i lektionen.",
  ),
  "svenska-f-3-2": p(
    "Eleverna skriver ”Det var en gång” och går direkt till flera händelser utan att läsaren får veta vem berättelsen handlar om eller var den börjar.",
    [7, 3, 9, 1],
    [
      "Visa två korta inledningar till samma berättelse: en som anger person, plats och begynnande problem och en som bara radar upp händelser.",
      "Tänk högt medan du skriver tre meningar på tavlan. Markera med var sin färg vem, var och vad som sätter berättelsen i rörelse.",
      "Ge eleverna en halvfärdig inledning där platsen saknas. De skriver en mening som passar och stryker under det ord som knyter meningen till resten.",
      "Ta bort skrivramen. Eleverna skriver en egen inledning till bilden av ett tomt tivoli och kontrollerar de tre delarna med fingrarna: vem, var, vad händer.",
    ],
    "Samla in inledningarna och sortera dem efter vilken av de tre delarna som saknas. Läs upp två anonymiserade exempel och låt eleverna ange vilken konkret uppgift varje mening gör.",
    "Om plats eller person bara nämns som lösryckta ord, modellera hur delen vävs in i en hel mening. Om alla tre delar finns, arbeta nästa gång med hur detaljer skapar stämning.",
    "Följande vecka skriver eleverna en ny inledning till en annan bild utan checklistan och markerar efteråt de tre funktionerna.",
  ),
  "svenska-4-6-1": p(
    "Eleverna väljer den mest spännande detaljen som huvudidé och återger resten av texten utan att visa vad flera stycken handlar om tillsammans.",
    [6, 7, 9, 5],
    [
      "Välj en faktatext på tre korta stycken. Skriv fyra möjliga huvudidéer: en för bred, en för smal, en felaktig och en som täcker texten.",
      "Modellera hur du prövar varje förslag mot alla stycken och stryker det som bara passar en detalj.",
      "Eleverna arbetar med en ny text: de skriver en huvudidé på högst tolv ord och väljer två meningar som belägg.",
      "Byt ut en detalj i texten och fråga om huvudidén fortfarande håller. Eleverna måste förklara varför eller formulera om den.",
    ],
    "Alla lämnar huvudidé plus två belägg på en lapp. Kontrollera om beläggen kommer från olika delar av texten och faktiskt stöder formuleringen.",
    "Om huvudidéerna blir ämnesetiketter som ”vulkaner”, jämför med en fullständig mening som uttrycker vad texten säger om vulkaner. Om de är precisa, ge en text med underförstådd huvudidé.",
    "Nästa vecka får eleverna återkalla kriterierna och formulera huvudidén i en ny text utan svarsalternativ.",
  ),
  "svenska-4-6-2": p(
    "Eleverna skriver en åsikt och upprepar den med andra ord, men ger inget skäl eller exempel som gör argumentet övertygande.",
    [7, 6, 9, 1],
    [
      "Visa två stycken om längre rast. Märk ut tes, skäl och belägg i det starkare stycket och låt det svagare sakna belägg.",
      "Tänk högt när du prövar om belägget verkligen stöder skälet: ”Fler vill ha rast” är inte belägg för att koncentrationen förbättras.",
      "Ge eleverna tre teser och sex skäl eller belägg. De parar ihop sådant som logiskt hör samman och motiverar ett bortvalt alternativ.",
      "Eleverna skriver ett eget stycke om mobiltelefoner med tes, ett skäl och ett konkret exempel eller faktauppgift.",
    ],
    "Låt eleverna ringa in tesen, stryka under skälet och sätta en ruta runt belägget. Be dem sedan skriva en mening om hur belägget stöder skälet.",
    "Om många saknar länken mellan skäl och belägg, modellera en därför-mening. Om strukturen håller, ge återkoppling (<em>feedback</em>) på beläggets relevans i stället för på antalet argument.",
    "Tre lektioner senare skriver eleverna ett nytt argumenterande stycke utan färgmarkeringar och jämför själva mot kriterierna.",
  ),
  "svenska-7-9-1": p(
    "Eleverna kan ange första- och tredjeperson men beskriver inte vilken information läsaren får eller hur närheten till en person förändras.",
    [6, 5, 7, 9],
    [
      "Ge klassen samma händelse i två versioner: en jag-berättare som missförstår situationen och en allvetande berättare som visar två personers tankar.",
      "Modellera en jämförelse i tre led: språkligt kännetecken, vilken information som blir möjlig och vilken effekt det får för läsaren.",
      "Eleverna markerar en mening i varje text som belägg och fyller i: ”I version A vet läsaren … medan version B … Därför …”.",
      "Låt eleverna skriva om sex meningar från jag-perspektiv till begränsad tredjeperson och notera vilken information som måste tas bort.",
    ],
    "Visa ett nytt textpar. Eleverna svarar enskilt vilket perspektiv som skapar störst osäkerhet och citerar en formulering som belägg.",
    "Om eleverna bara namnger pronomen, återvänd till frågan ”Vems tankar kan läsaren få veta?”. Om de kopplar form till effekt, låt dem jämföra en opålitlig berättare med en allvetande.",
    "Senare i arbetsområdet analyserar eleverna perspektivet i sin ordinarie roman utan jämförelsemallen.",
  ),
  "svenska-7-9-2": p(
    "Elevernas litterära svar består av ett påstående följt av ett citat; de förklarar inte hur ordvalet eller händelsen stöder tolkningen.",
    [7, 3, 9, 1],
    [
      "Välj ett kort stycke ur klassens novell och visa ett färdigt resonemang med påstående, textbelägg och förklaring av belägget.",
      "Tänk högt när du väljer mellan två citat och visar varför det kortare, mer precisa citatet ger bättre stöd.",
      "Ge eleverna två ofullständiga resonemang: i det ena saknas belägg och i det andra förklaring. De skriver den saknade delen.",
      "Eleverna väljer ett nytt stycke ur novellen och skriver ett eget resonemang utan meningsstarter.",
    ],
    "Be eleverna markera P, B och F i marginalen. Läs endast förklaringen och kontrollera om den faktiskt tolkar orden i citatet i stället för att återberätta handlingen.",
    "Om förklaringen återberättar, modellera hur ett enskilt ord i citatet kopplas till påståendet. Om kedjan håller, låt eleven pröva ett motbelägg.",
    "Vid nästa text skriver eleverna ett nytt stycke och jämför det med sitt första utifrån om varje belägg förklaras.",
  ),
  "svenska-gymnasiet-1": p(
    "Eleverna radar upp anafor, metaforer och retoriska frågor men visar inte hur valen fungerar för den aktuella publiken och talets syfte.",
    [6, 7, 9, 10],
    [
      "Välj 60–90 sekunder ur ett namngivet tal som klassen redan känner till. Ange talare, publik, situation och uttalat syfte innan analysen börjar.",
      "Modellera ett påstående om ett retoriskt val: citera exakt, beskriv mönstret och förklara vilken reaktion det rimligen försöker väcka hos just publiken.",
      "Visa en alternativ tolkning av samma formulering och pröva båda mot talets fortsättning. Markera vad texten stöder och vad som är en försiktig slutsats.",
      "Eleverna analyserar ett annat 30-sekundersavsnitt och skriver två kedjor: val → textbelägg → möjlig verkan → koppling till syftet.",
    ],
    "Eleverna lämnar en analyskedja. Kontrollera att verkan inte anges som ett säkert faktum om publikens känslor utan motiveras med formulering och situation.",
    "Om eleverna bara etiketterar stilfiguren, ge återkoppling (<em>feedback</em>) på länken mellan belägg och verkan. Om kedjan är stark, be dem pröva en rimlig alternativ tolkning.",
    "En vecka senare analyserar eleverna ett kort, okänt tal utan analysmallen och anger både huvudsaklig och alternativ tolkning.",
  ),
  "svenska-gymnasiet-2": p(
    "Eleverna skriver ett referat av källa A följt av ett referat av källa B men besvarar inte frågan genom att jämföra källornas påståenden.",
    [3, 7, 6, 9],
    [
      "Ge två korta källtexter om samma avgränsade fråga. Låt eleverna först skriva varje källas huvudtes i en rad och placera beläggen i en matris med gemensamma teman.",
      "Modellera hur ett stycke byggs kring temat i stället för källordningen: egen ämnesmening, källa A, relation till källa B och en försiktig slutsats.",
      "Ge ett stycke som staplar referat. Eleverna klipper isär meningarna, ordnar dem tematiskt och lägger till en jämförelsemarkör som ”däremot” eller ”på liknande sätt”.",
      "Eleverna skriver ett eget syntesstycke från ett nytt tema i matrisen och anger tydligt var källorna stöder respektive motsäger varandra.",
    ],
    "Kontrollera om varje stycke har en egen tematisk poäng och om båda källorna används för den poängen. Två korrekta referat utan relation räcker inte.",
    "Om texten fortfarande följer källa-för-källa, begränsa uppgiften till ett tema och modellera övergången. Om syntesen fungerar, rikta nästa återkoppling (<em>feedback</em>) mot slutsatsens räckvidd.",
    "Vid nästa skrivtillfälle gör eleverna en ny temamatris ur tre källor och skriver ett syntesstycke utan den färdiga mallen.",
  ),

  "matematik-f-3-1": p(
    "Eleverna löser 8 + 7 genom att räkna alla eller fortsätta på fingrarna och tappar tal när de passerar tio.",
    [6, 8, 7, 9],
    [
      "Lägg åtta röda och sju blå marker i två tiobrickor. Fråga hur många blå marker som behövs för att fylla den första brickan.",
      "Modellera 8 + 7 som 8 + 2 + 5. Flytta exakt två marker och skriv varje förändring bredvid bilden så att material och symboler visar samma steg.",
      "Eleverna gör 9 + 6 med marker och fyller i den halvfärdiga skrivningen 9 + __ + __ = 15.",
      "Ta bort markerna. Ge 7 + 8 och 6 + 9 blandat med summor under tio; eleverna ritar bara en tiobricka om de behöver stöd.",
    ],
    "Visa 8 + 5. Alla elever skriver vilket tal som delas, hur det delas och vilket tiotal som bildas. Be två elever förklara varför delningen hjälper.",
    "Om elever delar fel, återgå till tiobrickan och låt dem visa den saknade delen till tio. Om de väljer strategin säkert, jämför med att börja från det största talet.",
    "Efter tre dagar löser eleverna tre tiotalsövergångar utan marker och ritar efteråt hur en av dem kan förklaras.",
  ),
  "matematik-f-3-2": p(
    "Eleverna ser ordet ”fler” och adderar även när uppgiften frågar efter skillnaden mellan två antal.",
    [6, 7, 5, 9],
    [
      "Visa tre berättelser med samma tal, 12 och 7: lägga ihop två grupper, ta bort sju och jämföra gruppernas storlek.",
      "Modellera varje berättelse med staplar. Tänk högt om relationen innan du skriver räknesättet; ringa inte in signalord.",
      "Eleverna parar ihop sex berättelser med bilder av del–helhet, förändring eller jämförelse och motiverar ett par.",
      "Ge två nya textproblem utan bilder. Eleverna ritar relationen, skriver en beräkning och förklarar vad svaret betyder i berättelsen.",
    ],
    "Låt alla välja mellan tre relationsbilder till ett nytt problem och skriva en kort motivering. Kontrollera relationen före uträkningen.",
    "Om eleverna väljer efter ord, skriv om problemet med samma ord men annan relation och jämför. Om relationerna urskiljs, blanda problem där det okända finns på olika platser.",
    "Nästa vecka får eleverna tre blandade problem och ska välja relation utan att räknesättet eller bildtypen anges.",
  ),
  "matematik-4-6-1": p(
    "Eleverna tror att 1/8 är större än 1/4 eftersom åtta är större än fyra och kontrollerar inte att bråken avser lika stora helheter.",
    [6, 8, 5, 9],
    [
      "Visa två lika långa bråkremsor för 1/4 och 1/8. Låt eleverna förutsäga först och sedan placera delarna ovanpå varandra.",
      "Modellera tre sätt att jämföra: samma helhet med bild, referenspunkten 1/2 och gemensam nämnare. Ange när varje sätt är praktiskt.",
      "Eleverna sorterar 3/8, 5/8, 3/4 och 7/12 runt 1/2 och skriver vilket kännetecken de använde.",
      "Blanda par som har samma täljare, samma nämnare eller inget gemensamt. Eleverna måste välja jämförelsemetod före svaret.",
    ],
    "Visa 5/6 och 7/9. Eleverna skriver större, mindre eller lika och ger en representation eller beräkning som faktiskt avgör jämförelsen.",
    "Om resonemanget bygger på hela talen, återvänd till två lika stora helheter. Om svaret är korrekt men metoden tung, jämför två effektiva metoder.",
    "Fyra dagar senare jämför eleverna nya bråk utan bråkremsor och kontrollerar ett svar med en ritad modell.",
  ),
  "matematik-4-6-2": p(
    "Eleverna kan räkna ut en procentandel i ett block men väljer samma procedur när uppgiften i stället söker delen eller helheten.",
    [2, 7, 5, 9],
    [
      "Skriv tre frågor om samma situation: 25 procent av 200, 50 av 200 i procent och vilket heltal 50 är 25 procent av.",
      "Modellera en procentbar och märk helhet, del och andel. Tänk högt om vilken storhet som saknas innan någon formel väljs.",
      "Eleverna får nio uppgifter och sorterar dem efter okänd storhet. De löser en ur varje kategori med procentbaren som stöd.",
      "Blanda kategorierna. Eleverna skriver H, D och A vid givna värden och väljer metod utan färdig rubrik.",
    ],
    "Ge ett problem där helheten är okänd. Eleverna ska först märka ut del och andel och sedan förklara varför division, inte 25-procentsberäkning, behövs.",
    "Om markeringen är fel, arbeta med språk och procentbar innan beräkning. Om markeringen är rätt men uträkningen fel, ge ett genomarbetat exempel (<em>worked example</em>) på just den kategorin.",
    "Nästa vecka blandas procentproblemen med bråk- och decimaluppgifter så att eleverna åter måste välja kategori och metod.",
  ),
  "matematik-7-9-1": p(
    "Eleverna säger att en term ”byter sida och byter tecken” men kan inte förklara varför samma operation måste göras i båda leden.",
    [6, 7, 9, 1],
    [
      "Visa 3x + 5 = 20 tillsammans med en balansbild. Fråga vad som händer om fem tas bort på bara ena sidan.",
      "Modellera lösningen rad för rad. Skriv operationen −5 på båda sidor och formulera beslutet: målet är att isolera 3x utan att ändra likheten.",
      "Eleverna kompletterar en lösning där operationerna saknas och förklarar varför varje ny rad är ekvivalent med den föregående.",
      "Ge ekvationerna 4x − 7 = 13 och 18 = 3x + 6 blandat. Eleverna väljer första operation och kontrollerar lösningen genom insättning.",
    ],
    "Visa en felaktig lösning där bara vänsterledet ändras. Alla markerar första felaktiga raden och skriver vilken likvärdig operation som saknas.",
    "Om regeln fortfarande uttrycks som att flytta, återgå till balansbild och operation på båda led. Om innebörden håller, ta bort balansbilden och öka antalet steg.",
    "En vecka senare löser och kontrollerar eleverna en ekvation med parentes utan frasen ”byt sida”.",
  ),
  "matematik-7-9-2": p(
    "Eleverna kallar varje rät linje proportionell och kontrollerar inte om grafen går genom origo eller om kvoten y/x är konstant.",
    [6, 8, 5, 9],
    [
      "Visa två tabeller och två grafer: y = 3x och y = 3x + 4. Markera motsvarande värden mellan tabell, graf och formel.",
      "Modellera en kontrollkedja: går grafen genom origo, är y/x konstant och har formeln formen y = kx?",
      "Eleverna parar ihop sex tabeller, grafer och formler och skriver vilket kännetecken som avgör proportionellt eller bara linjärt.",
      "Ge ett taxipris och ett kilopris. Eleverna väljer modell, förklarar startvärdets betydelse och ritar graf.",
    ],
    "Visa en ny graf som nästan ser ut att gå genom origo. Eleverna ska använda en avläsbar punkt och formeln för att motivera klassificeringen.",
    "Om eleverna går på utseendet, låt dem översätta till tabell och formel. Om klassificeringen är säker, lägg till ett icke-linjärt samband med liknande värden.",
    "Senare blandas proportionella, linjära och exponentiella samband utan kategoriangivelse.",
  ),
  "matematik-gymnasiet-1": p(
    "Eleverna väljer exponentiell modell så snart ordet procent förekommer, även när ökningen anges i procentenheter eller varierar mellan perioderna.",
    [6, 5, 9, 10],
    [
      "Ge tre dataserier: konstant differens, konstant kvot och en serie som bara ungefär följer en modell. Dölj rubrikerna.",
      "Modellera hur första- och andradifferenser samt kvoter beräknas och kopplas till linjär, exponentiell eller kvadratisk modell.",
      "Eleverna analyserar en tabell över befolkning eller pris, väljer modell och skriver vilket numeriskt mönster som stöder valet.",
      "Låt dem jämföra modellens prognos med ett senare faktiskt värde och formulera ett antagande som begränsar extrapoleringen.",
    ],
    "Ge en ny tabell med brus. Eleverna väljer modell och måste nämna både ett stödjande mönster och en avvikelse; modellnamnet utan belägg räcker inte.",
    "Om valet styrs av uppgiftens ord, gå tillbaka till differens och kvot. Om modellen motiveras väl, rikta återkopplingen (<em>feedback</em>) mot antaganden och rimligt giltighetsintervall.",
    "Vid nästa område får eleverna välja modell till en okänd datamängd och jämföra prognosen med ett håll-out-värde.",
  ),
  "matematik-gymnasiet-2": p(
    "Eleverna kan beräkna f′(3) men skriver bara ett tal och kopplar inte värdet till momentan förändringshastighet eller rätt enhet.",
    [6, 8, 7, 9],
    [
      "Utgå från s(t), sträckan i meter efter t sekunder. Visa samtidigt grafen, en tangent vid t = 3 och uttrycket s′(3).",
      "Modellera tolkningen i fyra delar: storhet, tidpunkt, riktning och enhet – ”vid tre sekunder ökar sträckan med ungefär … meter per sekund”.",
      "Eleverna matchar derivatavärden med tangenter och muntliga tolkningar; lägg in ett icke-exempel med fel enhet.",
      "Ge en kostnadsfunktion och en temperaturfunktion. Eleverna beräknar ett derivatavärde och skriver en fullständig tolkning i respektive sammanhang.",
    ],
    "Visa f′(5) = −2 för en vattennivå mätt i centimeter per timme. Eleverna skriver vad minus, tvåan och enheten betyder.",
    "Om enheten saknas, kommentera bara enhetsledet och låt eleven revidera. Om tolkningen är korrekt, fråga över vilket intervall en lokal linjär approximation är rimlig.",
    "En vecka senare tolkar eleverna en derivata direkt ur en graf utan att först utföra symbolisk derivering.",
  ),

  "engelska-f-3-1": p(
    "Eleverna väljer rätt bild när läraren säger ordet men kan inte själva säga cup, spoon, plate, chair, door och window.",
    [4, 5, 6, 9],
    [
      "Lägg sex verkliga föremål eller tydliga bilder på bordet. Säg varje ord i en kort fras, exempelvis ”a red cup”, och låt eleverna härma en gång.",
      "Dölj ordkorten men låt föremålen ligga kvar. Peka i slumpad ordning och låt alla först viska ordet och sedan säga en kort fras.",
      "Ta bort föremålen två i taget. Fråga ”What is missing?” så att eleverna måste återkalla ordet utan bildstöd.",
      "Visa ett kök som inte använts tidigare. Eleverna pekar och säger minst tre egna fraser med målorden.",
    ],
    "Visa sex nya bilder en i taget. Varje elev säger ordet utan svarsalternativ och använder ett av orden i ”I can see …”.",
    "Om elever känner igen men inte kan säga ordet, minska antalet till tre och gör en ny återkallningsrunda. Om orden kommer säkert, variera färg, antal och placering.",
    "Återkalla samma ord efter två dagar och igen veckan därpå i en ny bild av ett klassrum eller kök.",
  ),
  "engelska-f-3-2": p(
    "Eleverna kan upprepa ”How are you?” men väntar på lärarens ledtråd för att svara och ställa en följdfråga.",
    [7, 3, 9, 5],
    [
      "Spela upp en dialog med tre turer: hälsning, fråga och svar plus motfråga. Visa tre enkla bildsymboler som stöd för turerna.",
      "Modellera båda rollerna med en handdocka och tänk högt på svenska om vilken replik som passar efter föregående tur.",
      "Eleverna fyller i en saknad replik i två dialoger och övar sedan med replikkort där ett kort vänds bort varje gång.",
      "Ta bort korten. Eleverna samtalar i par och byter en uppgift, exempelvis känsla eller favoritfärg, så att dialogen inte bara memoreras som ljudföljd.",
    ],
    "Lyssna på fyra par och notera om eleven ger ett relevant svar och lämnar tillbaka turen. Låt sedan alla spela in eller framföra tre turer.",
    "Om turordningen brister, återinför bildsymbolerna men inte hela replikerna. Om den fungerar, lägg till en oväntad följdfråga.",
    "Nästa vecka genomför eleverna samma samtalsstruktur med ett nytt innehåll utan replikkort.",
  ),
  "engelska-4-6-1": p(
    "Eleverna känner igen because, people, their, where, were, could, would och should i text men stavar eller använder dem fel i egna meningar.",
    [4, 5, 6, 9],
    [
      "Välj åtta högfrekventa ord ur den text klassen läser. Visa kort hur varje ord fungerar i en meningsram, inte som en fristående glosa.",
      "Dölj orden. Läs en mening med lucka och låt eleverna skriva ordet på miniwhiteboard innan det visas.",
      "Blanda stavningsåterkallning med betydelseval: eleverna skriver ordet, jämför because och therefore och rättar direkt mot korrekt form.",
      "Eleverna skriver fyra egna meningar som tillsammans använder alla åtta orden och stryker under den grammatiska funktion de fyller.",
    ],
    "Diktera fyra nya meningar med luckor. Kontrollera både återkallad stavning och om ordet passar meningen.",
    "Om stavningen är svag men funktionen rätt, gör kortare återkallning av ordformen. Om ordet stavas rätt men används fel, jämför två kontrasterande meningar.",
    "Återkom till orden efter två, fem och tio dagar i nya läs- och skrivuppgifter.",
  ),
  "engelska-4-6-2": p(
    "Eleverna skriver många meningar som börjar med ”It is” och ordnar detaljer i den ordning de kommer på dem.",
    [7, 3, 6, 9],
    [
      "Visa en beskrivning av ett rum med tydlig ordning från helhet till vänster–höger och sambandsord som first, next to och finally.",
      "Markera varje menings funktion i marginalen. Modellera hur en detalj flyttas så att läsaren kan följa rummet utan bild.",
      "Ge eleverna en bild och sex meningar i oordning. De ordnar meningarna och motiverar två övergångar.",
      "Eleverna skriver en egen beskrivning av en annan bild med en ämnesmening, minst tre positionsord och en avslutning.",
    ],
    "Byt texter utan att visa bilden. Läsaren ritar en enkel skiss; stora skillnader visar var ordning eller positionsord är otydliga.",
    "Om flera skisser blir fel på samma plats, modellera just den övergången. Om texten går att följa, ge återkoppling (<em>feedback</em>) på variation och precision.",
    "Vid nästa skrivuppgift planerar eleverna ordningen själva utan färdiga meningar.",
  ),
  "engelska-7-9-1": p(
    "Eleverna klarar isolerade tempusövningar men växlar mellan past simple och present i en berättelse utan att tidsrelationen förändras.",
    [6, 7, 5, 9],
    [
      "Visa en tidslinje och ett kort berättelsestycke. Koppla varje verbform till händelseordning: bakgrund, pågående händelse och avbrott.",
      "Modellera hur du väljer mellan past simple och past continuous och varför ett omotiverat presensskifte stör tidslinjen.",
      "Eleverna rättar ett stycke med fem tempusfel och skriver vid varje ändring vilken tidsrelation som kräver formen.",
      "De skriver sedan åtta meningar till en bildsekvens och använder minst ett motiverat skifte mellan bakgrund och händelse.",
    ],
    "Ta bort verben ur tre meningar och låt eleverna välja form samt rita den tidsrelation som valet uttrycker.",
    "Om valet bygger på ett enskilt tidsord, använd en mening där tidsordet inte avgör formen. Om tidsrelationerna förstås, arbeta med stilistiskt historiskt presens som medvetet val.",
    "En vecka senare redigerar eleverna tempus i en ny egen text utan den färdiga tidslinjen.",
  ),
  "engelska-7-9-2": p(
    "Eleverna svarar ”I agree” eller ger en åsikt men utvecklar inte skälet och kan inte bemöta ”Why?” eller en invändning.",
    [7, 4, 9, 1],
    [
      "Modellera ett 30-sekunderssvar i fyra delar: ståndpunkt, skäl, exempel och svar på en följdfråga. Skriv bara stödorden på tavlan.",
      "Spela upp ett kort svar som saknar exempel. Eleverna identifierar luckan och föreslår ett konkret exempel på engelska.",
      "Eleverna får en enkel fråga och 45 sekunder att återkalla strukturen och skriva fyra stödord, inte ett manus.",
      "I par framför de svaret; lyssnaren ställer en av tre följdfrågor och talaren måste utveckla eller precisera sitt skäl.",
    ],
    "Låt varje elev spela in ett minutlångt svar. Kontrollera om ståndpunkt, skäl, exempel och relevant svar faktiskt hör ihop.",
    "Om följdfrågan leder till upprepning, modellera skillnaden mellan att upprepa och att utveckla. Om strukturen håller, ta bort de färdiga följdfrågorna.",
    "Vid nästa muntliga aktivitet används samma struktur om ett nytt ämne utan stödorden på tavlan.",
  ),
  "engelska-gymnasiet-1": p(
    "Eleverna skriver med korrekt grammatik men använder samma ordval och meningsform i ett mejl till en vän som i en formell ansökan.",
    [6, 5, 7, 9],
    [
      "Visa två meddelanden med samma innehåll men olika mottagare: ett till en vän och ett till en organisation. Markera hälsning, modalverb, sammandragningar och avslutning.",
      "Modellera hur syfte, relation och kanal styr ett konkret val, exempelvis ”Can you …?” jämfört med ”I would appreciate it if …”.",
      "Eleverna sorterar tolv formuleringar efter register och placerar tre gränsfall på en skala snarare än i två absoluta lådor.",
      "De skriver om ett informellt klagomål till ett formellt mejl och kommenterar fyra ändringar med mottagare eller syfte.",
    ],
    "Ge en ny situation och två formuleringar. Eleverna väljer den mest lämpliga och motiverar med ett språkligt drag och relationen till mottagaren.",
    "Om motiveringen bara säger ”mer formell”, kräv att eleven namnger ändringen. Om valet är säkert, variera kanal eller maktrelation så att begränsningarna blir synliga.",
    "Senare skriver eleverna två korta versioner av samma budskap för olika mottagare utan språkbank.",
  ),
  "engelska-gymnasiet-2": p(
    "Eleverna återger två engelskspråkiga källor separat men använder dem inte för att stödja, begränsa eller invända mot ett eget påstående.",
    [6, 7, 9, 10],
    [
      "Välj två korta källutdrag som ger olika svar på en avgränsad fråga. Eleverna skriver varje källas påstående, belägg och begränsning i en tabell.",
      "Modellera ett stycke där ett eget påstående följs av stöd från källa A och en precisering eller invändning från källa B.",
      "Visa en orimligt stark slutsats och tänk högt om hur urval och källtyp kräver ord som suggests, indicates eller in this sample.",
      "Eleverna skriver ett eget stycke där båda källorna får en tydlig funktion och där motargumentet besvaras, inte bara nämns.",
    ],
    "Kontrollera med tre frågor: Finns ett eget påstående? Har båda källorna en angiven funktion? Är slutsatsen svagare eller lika stark som beläggen tillåter?",
    "Om källorna staplas, låt eleven skriva en relationsmening innan resten revideras. Om relationen håller, ge återkoppling (<em>feedback</em>) på slutsatsens avgränsning.",
    "I nästa uppgift syntetiserar eleverna två nya utdrag utan den ifyllda tabellen.",
  ),

  "biologi-f-3-1": p(
    "Eleverna säger att ett frö behöver jord och ljus för att gro eftersom de blandar ihop groning med den fortsatta växtens behov.",
    [6, 7, 9, 10],
    [
      "Förbered fyra påsar med lika frön: vatten och värme, torrt och varmt, vått och kallt samt vått och varmt men mörkt. Håll frösort och tid lika.",
      "Låt eleverna förutsäga varje utfall och modellera skillnaden mellan frågorna ”Vad krävs för groning?” och ”Vad krävs för fortsatt tillväxt?”.",
      "Följ påsarna med foto och enkel tabell. Eleverna jämför särskilt det mörka och det ljusa villkoret i stället för att bara beskriva en påse.",
      "Efter groning flyttas några groddar till ljus. Eleverna reviderar sin förklaring och skiljer fröets lagrade näring från växtens senare behov av ljus.",
    ],
    "Visa resultaten utan etiketter. Eleverna anger vilket villkor som saknades i varje misslyckad påse och vilket påstående resultaten inte kan avgöra.",
    "Om eleverna fortfarande kräver ljus för groning, jämför de två våta och varma påsarna. Om slutsatsen är korrekt, diskutera att försöket gäller den använda frösorten och tiden.",
    "En vecka senare får eleverna förklara vad som händer med ett frö i fuktigt papper i ett mörkt skåp och vad som behöver ändras efter groningen.",
  ),
  "biologi-f-3-2": p(
    "Eleverna säger att djur bor där de ”trivs” men kopplar inte päls, fötter, näbb eller kroppsform till konkreta villkor i livsmiljön.",
    [6, 8, 5, 9],
    [
      "Visa tydliga bilder av säl, mullvad och hackspett tillsammans med vatten, jord och trädstam. Markera en kroppsdel per djur.",
      "Modellera kedjan egenskap → funktion → miljö: ”Sälens strömlinjeformade kropp minskar motståndet när den simmar i vatten.”",
      "Eleverna parar ihop sex egenskapskort med funktion och miljö. Lägg in ett rimligt men felaktigt par som de måste avvisa.",
      "Visa ett nytt djur, exempelvis snöskohare. Eleverna väljer två synliga egenskaper och skriver vad de kan hjälpa djuret att göra.",
    ],
    "Varje elev ritar en pilkedja med egenskap, funktion och livsmiljö för ett nytt djur. Kontrollera att funktionen inte bara upprepar egenskapen.",
    "Om svaren blir ”den har päls för att den bor där”, modellera en mätbar funktion som värme eller rörelse. Om kedjan håller, jämför två djur i samma miljö.",
    "Nästa vecka återkallar eleverna kedjan och använder den på ett djur som inte fanns bland bilderna.",
  ),
  "biologi-4-6-1": p(
    "Eleverna ritar en kedja av vem som äter vem men säger att energin går runt i ett kretslopp och glömmer producentens och nedbrytarens roller.",
    [6, 8, 4, 9],
    [
      "Bygg kedjan sol → gräs → gräshoppa → groda med kort. Använd en separat färg för energins riktning och materia som återförs.",
      "Modellera pilens betydelse: pilen går från det som innehåller energi till organismen som tar emot den, inte mot det som blir uppätet.",
      "Eleverna rättar en felvänd kedja och lägger till svamp som nedbrytare. De förklarar vad svampen får och vad som återförs till marken.",
      "Ge ett enkelt näringsnät. Eleverna förutsäger en följd om gräshoppor minskar och markerar vilka länkar som stöder förutsägelsen.",
    ],
    "Dölj modellen. Eleverna ritar kedjan, anger energins ursprung och skriver varför nedbrytaren inte gör energiflödet cirkulärt.",
    "Om pilarna vänds fel, återgå till frågan ”Vem får energin?”. Om flödet förstås, lägg till att mycket energi omvandlas till värme i varje led.",
    "Efter några dagar får eleverna bygga en ny kedja i havsmiljö och förklara samma energiprincip.",
  ),
  "biologi-4-6-2": p(
    "Eleverna kan namnge lungor, hjärta och blod men beskriver dem som tre separata delar utan transport till och från cellerna.",
    [3, 8, 7, 9],
    [
      "Visa en förenklad kroppskarta med lungor, hjärta, blodkärl och en muskelcell. Ta bort andra organ som inte behövs för frågan.",
      "Modellera en syremolekyls väg med en flyttbar markör och säg vad som händer vid varje övergång. Modellera sedan koldioxidens väg tillbaka.",
      "Eleverna ordnar sex stegkort och upptäcker ett saknat steg mellan blod och cell. De ritar pilar och skriver transporterat ämne vid varje pil.",
      "Låt eleverna förklara varför både andning och blodomlopp måste öka när en person springer.",
    ],
    "Ge en tom karta. Eleverna ritar syrets väg och förklarar vad som skulle hända med cellerna om blodflödet till muskeln stoppades.",
    "Om organen bara räknas upp, ställ följdfrågan ”Vad transporteras vart?”. Om systemet hänger ihop, lägg till näring från tarmen som en andra transport.",
    "Nästa vecka rekonstruerar eleverna modellen utan stegkort och jämför syre- och koldioxidvägen.",
  ),
  "biologi-7-9-1": p(
    "Eleverna kan två reaktionsformler men tror att växter bara fotosyntetiserar och att cellandning är samma sak som att andas med lungor.",
    [6, 8, 5, 9],
    [
      "Placera fotosyntes och cellandning i en jämförelsetabell med plats i cellen, reaktanter, produkter och energiförändring.",
      "Modellera hur samma kolatom kan finnas i koldioxid, byggas in i glukos och senare återgå till koldioxid. Skilj materians kretslopp från energins flöde.",
      "Eleverna sorterar påståenden som ”sker bara i ljus” och ”sker i växtceller” till rätt process och rättar två avsiktliga missuppfattningar.",
      "Ge ett scenario med en växt i mörker. Eleverna förutsäger vilka processer som fortsätter och hur gasutbytet påverkas.",
    ],
    "Eleverna ritar båda processerna ur minnet och svarar varför en växt kan avge koldioxid i mörker utan att ha slutat leva.",
    "Om processerna blir spegelvända ordlistor, följ en kolatom och energin var för sig. Om de skiljs korrekt, analysera nettogasutbyte i olika ljusnivåer.",
    "En vecka senare används processerna för att förklara massförändring i en groende ärta.",
  ),
  "biologi-7-9-2": p(
    "Eleverna skriver att enskilda djur förändrar sig för att överleva och för sedan den förvärvade egenskapen vidare.",
    [6, 7, 5, 9],
    [
      "Visa en skalbaggepopulation med ärftlig variation i färg före och efter predation. Håll miljön och generationerna tydligt åtskilda.",
      "Modellera förklaringen i fyra led: variation finns redan, egenskapen påverkar överlevnad eller fortplantning, egenskapen ärvs och frekvensen ändras över generationer.",
      "Eleverna jämför en korrekt populationsförklaring med meningen ”skalbaggarna blev mörka för att gömma sig” och markerar exakt vad som saknas.",
      "De använder modellen på antibiotikaresistens och anger vad som varierar, vad som selekterar och vad som förändras i populationen.",
    ],
    "Ge ett nytt fall med finknäbbar. Eleverna skriver fyra led och får inte använda formuleringen ”arten anpassade sig” utan mekanism.",
    "Om behov anges som orsak, återgå till variationen före selektionen. Om mekanismen är korrekt, lägg till slumpmässig genetisk drift som alternativ för liten population.",
    "Senare jämför eleverna naturligt urval med individuell acklimatisering utan stödmallen.",
  ),
  "biologi-gymnasiet-1": p(
    "Eleverna kan orden transkription och translation men tappar var processerna sker och hur en förändrad DNA-sekvens kan påverka aminosyrasekvens och proteinfunktion.",
    [3, 8, 7, 9],
    [
      "Använd en kort DNA-sekvens och visa endast de nödvändiga stegen DNA → pre-mRNA → mRNA → aminosyror → veckat protein.",
      "Modellera basparning och kodonläsning på samma sekvens. Markera cellkärna och ribosom så att plats och process inte blandas.",
      "Eleverna kompletterar en halvfärdig kedja och jämför sedan en tyst mutation, en missensemutation och en deletion i samma kodande sekvens.",
      "De förutsäger följden på varje nivå och anger var förutsägelsen blir osäker, exempelvis proteinets slutliga funktion.",
    ],
    "Ge en ny enkel substitution. Eleverna skriver den nya mRNA- och aminosyrasekvensen och skiljer säker följd från möjlig funktionell effekt.",
    "Om riktning eller basparning är fel, återgå till ett enda steg. Om kedjan är säker, utöka modellen med splitsning eller reglerande DNA.",
    "Nästa vecka rekonstruerar eleverna informationsflödet och analyserar en ny mutation utan den färgkodade modellen.",
  ),
  "biologi-gymnasiet-2": p(
    "Eleverna förklarar populationsförändring med en enda faktor och behandlar korrelationen mellan rovdjur och bytesdjur som bevis för direkt orsak.",
    [6, 9, 10, 5],
    [
      "Ge en tidsserie för hare, lodjur och vintertemperatur. Låt eleverna först beskriva mönstret utan att använda orsaksord.",
      "Modellera ett kausalt diagram med föda, predation, sjukdom och täthetsberoende. Markera fördröjningar och möjliga återkopplingsslingor (<em>feedback loops</em>).",
      "Eleverna formulerar två konkurrerande förklaringar till en minskning och anger vilken ytterligare mätning som skulle skilja dem åt.",
      "De testar hur förklaringen förändras när en ny uppgift om födotillgång eller jakt läggs till.",
    ],
    "Eleverna lämnar en förklaring med minst två faktorer, riktade samband och en uttrycklig osäkerhet. En kurva som följer en annan räcker inte som orsak.",
    "Om sambanden bara räknas upp, be eleven ange riktning och mekanism. Om modellen är sammanhängande, pröva den mot en period där kurvorna inte följs åt.",
    "I nästa moment analyserar eleverna en annan population och återkallar själva vilka alternativa förklaringar som bör prövas.",
  ),

  "fysik-f-3-1": p(
    "Eleverna säger att skuggan alltid blir större när föremålet flyttas, utan att ange om det flyttas mot lampan eller mot väggen.",
    [6, 7, 9, 10],
    [
      "Ställ en ficklampa, en figur och en vit skärm i rad. Markera de tre platserna på bordet så att bara en position ändras åt gången.",
      "Modellera ljusstrålar med två snören från lampan förbi figurens kanter till skärmen och förutsäg skuggans gränser.",
      "Eleverna flyttar figuren närmare lampan och sedan närmare skärmen, ritar före–efter och mäter skuggans höjd.",
      "De får en ny uppställning och skriver förutsägelse före mätning samt en förklaring med avstånd och spridning.",
    ],
    "Visa två möjliga bilder av skuggan när figuren flyttas mot lampan. Alla väljer och förklarar med strålarnas väg.",
    "Om eleverna bara återger regeln större eller mindre, låt dem rita två kantstrålar. Om modellen fungerar, ändra ljuskällans storlek och diskutera suddig kant.",
    "Efter några dagar förutsäger eleverna skuggan i en ny placering utan att först prova praktiskt.",
  ),
  "fysik-f-3-2": p(
    "Eleverna säger att ljudet i sig blir svagare utan att skilja mellan ljudkällan, avståndet och hur ljudet uppfattas med hörseln.",
    [2, 5, 9, 10],
    [
      "Använd en ljudkälla med oförändrad och säker volym. Markera platser en, tre och sex meter från källan i ett tyst rum.",
      "Låt eleverna förutsäga var ljudet uppfattas starkast. Modellera orden ljudkälla, avstånd och uppfatta utan att påstå att örat mäter exakta ljudnivåer.",
      "Spela samma korta ljud från varje försökspunkt. Eleverna visar starkare, svagare eller ungefär lika och dokumenterar plats och upplevelse med ord eller bild.",
      "Jämför resultaten och låt eleverna formulera en slutsats som gäller den använda ljudkällan och miljön. Diskutera varför bakgrundsljud kan ändra vad man hör.",
    ],
    "Spela samma ljud nära och längre bort. Eleverna anger vilket som uppfattas starkast och pekar ut vad som hölls lika mellan försöken.",
    "Om eleverna tror att olika avstånd prövades med olika ljud, upprepa med samma inspelning och volym. Om jämförelsen fungerar, lägg till bakgrundsljud som en ny faktor.",
    "Nästa vecka planerar eleverna en enkel jämförelse av samma ljud på två avstånd och anger vad som måste hållas lika.",
  ),
  "fysik-4-6-1": p(
    "Eleverna kopplar batteri och lampa men felsöker genom att flytta delar på måfå och ser inte att strömvägen måste vara sluten genom lampans två kontakter.",
    [6, 7, 5, 9],
    [
      "Visa en fungerande krets med batteri, två sladdar och glödlampa. Rita en enkel motsvarande kretsskiss bredvid varje fysisk koppling.",
      "Modellera en systematisk kontroll: följ vägen från ena batteripolen genom lampan och tillbaka till den andra polen.",
      "Eleverna får tre avsiktligt felkopplade kretsar: öppen väg, båda sladdar på samma kontakt och trasig komponent. De ändrar en sak i taget.",
      "De bygger sedan en krets från en skiss och skriver vilket test som visar om felet ligger i sladden, lampan eller batteriet.",
    ],
    "Visa en bild av en icke fungerande koppling. Eleverna markerar avbrottet och ritar exakt en ändring som sluter kretsen.",
    "Om felsökningen är slumpmässig, återinför följ-vägen-rutinen. Om den är systematisk, lägg till en strömbrytare eller två lampor.",
    "Följande vecka bygger eleverna en ny krets enbart från kretsschema och dokumenterar felsökningsordningen.",
  ),
  "fysik-4-6-2": p(
    "Eleverna säger att ett föremål ”har kraft” eller att rörelseriktningen alltid visar kraftens riktning.",
    [6, 8, 5, 9],
    [
      "Visa tre bilder: bok på bord, boll som sparkas och cykel som bromsar. Rita kraftpilar från omgivningen till föremålet.",
      "Modellera fyra frågor: vilket föremål analyseras, vad påverkar det, åt vilket håll verkar kraften och hur ändras rörelsen?",
      "Eleverna jämför en boll under själva sparken med bollen efter att foten lämnat den. De tar bort fotkraften i det andra kraftdiagrammet.",
      "Ge nya fall med kundvagn som accelererar, rullar jämnt och bromsar. Eleverna kopplar nettokraftens riktning till förändringen av rörelsen.",
    ],
    "Visa ett föremål som rör sig åt höger men bromsar. Eleverna ritar nettokraftens riktning och förklarar varför den inte följer rörelsen.",
    "Om pilar ritas som rörelsepilar, låt eleverna namnge det andra föremålet som utövar varje kraft. Om det fungerar, jämför balanserade krafter vid vila och jämn fart.",
    "Senare analyserar eleverna ett nytt vardagsfall utan de fyra frågorna utskrivna.",
  ),
  "fysik-7-9-1": p(
    "Eleverna tror att en puck som rör sig med konstant fart måste ha en framåtriktad nettokraft.",
    [6, 7, 5, 9],
    [
      "Visa fyra situationer med samma rörelseriktning men olika förändring: ökad fart, minskad fart, sväng och konstant hastighet.",
      "Modellera kraftdiagrammet separat från hastighetspilen och koppla nettokraft till acceleration, inte till rörelse i sig.",
      "Eleverna sorterar fallen efter acceleration och ritar därefter möjliga kraftdiagram. De jämför två fall med samma hastighet men olika nettokraft.",
      "Ge en puck på nästan friktionsfri yta och en bil på väg. Eleverna förklarar varför olika krafter kan ge samma konstanta hastighet.",
    ],
    "Visa en boll i högsta punkten av ett kast. Eleverna ritar hastighet och krafter var för sig och motiverar vad som är noll och inte.",
    "Om rörelse och kraft fortfarande sammanblandas, jämför två kontrasterande fall med samma rörelse. Om nettokraften förstås, lägg till tvådimensionell cirkelrörelse.",
    "En vecka senare analyserar eleverna tre blandade rörelsefall utan kategorirubriker.",
  ),
  "fysik-7-9-2": p(
    "Eleverna säger att energi ”förbrukas” i en apparat och blandar ihop energiform, energibärare och vart energin överförs.",
    [6, 8, 7, 9],
    [
      "Välj en vattenkokare. Rita systemgräns och modellera energikedjan från elektrisk överföring till ökad termisk energi i vatten och omgivning.",
      "Skilj tre kolumner: energilager eller form, överföringssätt och objekt som tar emot energin. Placera vanliga ord i rätt kolumn.",
      "Eleverna bygger en kedja för ficklampa och rättar icke-exemplet ”batteriet innehåller elektricitet som blir ljus”.",
      "De jämför nyttig energiöverföring och spridning till omgivningen för cykelbroms eller mobiltelefon.",
    ],
    "Ge en hårtork. Eleverna ritar systemgräns och redovisar minst två energiöverföringar utan att skriva att energi försvinner.",
    "Om endast en ordkedja ges, fråga vilket objekt som ändrar energilager. Om bevarandet förstås, låt eleverna kvantifiera verkningsgrad.",
    "Nästa vecka följer eleverna energi genom ett nytt system och återkallar de tre kolumnerna själva.",
  ),
  "fysik-gymnasiet-1": p(
    "Eleverna tolkar en stigande sträcka–tid-graf som positiv acceleration och läser grafens höjd när de borde läsa lutningen.",
    [6, 8, 5, 9],
    [
      "Visa en fysisk rörelse på rak bana samtidigt med läge–tid-graf. Pausa vid tre intervall och koppla branthet till hastighet.",
      "Modellera översättningen läge–tid → hastighet–tid → acceleration–tid för ett styckvis enkelt fall och ange vad area respektive lutning betyder.",
      "Eleverna matchar fyra rörelsebeskrivningar med diagram och motiverar med lutning eller area, inte med grafens allmänna form.",
      "De skapar själva en rörelse framför sensorn som följer ett givet läge–tid-diagram och förklarar avvikelser.",
    ],
    "Ge ett okänt läge–tid-diagram. Eleverna skissar hastighet–tid och beskriver en möjlig fysisk rörelse intervall för intervall.",
    "Om grafhöjd och lutning blandas, jämför två parallella segment på olika höjd. Om översättningen fungerar, lägg till en diskontinuitet och pröva fysisk rimlighet.",
    "En vecka senare översätter eleverna mellan diagram utan rörelsesensorn eller färgmarkeringarna.",
  ),
  "fysik-gymnasiet-2": p(
    "Eleverna ritar fältlinjer som partikelbanor och använder Coulombs lag parvis utan att se hur fältet beskriver kraft per laddning i varje punkt.",
    [6, 8, 7, 9],
    [
      "Visa en positiv punktladdning. Modellera hur en liten positiv testladdning definierar fältriktning i flera punkter och skilj test från faktisk rörelse.",
      "Koppla fältlinjebild, vektorer och E = F/q punkt för punkt. Markera att linjetäthet visar relativ styrka, inte antal fältlinjer i naturen.",
      "Eleverna ritar superpositionen från två lika positiva laddningar i fem givna punkter innan de skissar hela fältet.",
      "Placera en negativ laddning i en ny punkt. Eleverna anger fält, kraft och möjlig initial acceleration som tre skilda storheter.",
    ],
    "Ge ett fältdiagram. Eleverna markerar var styrkan är störst, riktningen för E och kraften på både positiv och negativ testladdning.",
    "Om fältlinje blir bana, fråga vad som ändras om partikelns initialhastighet är tvärs fältet. Om fältbegreppet håller, koppla till potential och ekvipotentialytor.",
    "Senare löser eleverna ett nytt två-laddningsfall utan den förtryckta punktmallen.",
  ),

  "kemi-f-3-1": p(
    "Eleverna sorterar föremål efter färg eller användning även när uppgiften gäller om materialet är magnetiskt eller suger upp vatten.",
    [2, 6, 5, 9],
    [
      "Lägg fram träbit, gem, plastlock, tyg, aluminiumfolie och svamp. Ange en enda egenskap: dras till magnet.",
      "Modellera ett rättvist test av två föremål med samma magnet och avstånd och skriv resultat i ja/nej-tabell.",
      "Eleverna testar alla föremål och sorterar efter resultat, inte utseende. Därefter upprepas sorteringen med egenskapen suger upp vatten.",
      "Visa ett gränsfall, exempelvis ett plastöverdraget gem. Eleverna måste ange vilket material eller vilken egenskap testet faktiskt avslöjar.",
    ],
    "Ge ett nytt föremål. Eleverna förutsäger kategori, genomför det angivna testet och ändrar vid behov sin sortering med motivering.",
    "Om sorteringen följer tycke eller färg, upprepa frågan vilken mätbar egenskap som gäller. Om den är säker, låt eleverna skapa en tvåegenskapstabell.",
    "Nästa lektion sorterar eleverna nya föremål och återkallar själva hur ett jämförbart test görs.",
  ),
  "kemi-f-3-2": p(
    "Eleverna kallar all förändring av vatten för att det ”försvinner” och skiljer inte smältning, frysning och avdunstning.",
    [6, 8, 7, 9],
    [
      "Visa isbit i skål, vatten som fryser och en våt markering som torkar. Skriv startform och slutform bredvid varje observation.",
      "Modellera språket: smälta är fast till flytande, frysa är flytande till fast och avdunsta är flytande vatten som blir gas i luften.",
      "Eleverna ordnar bildkort före–efter och lägger rätt processord mellan bilderna. Ett kort där vatten hälls bort används som icke-exempel.",
      "De ritar vart vattnet tar vägen i varje fall och anger vad som kan observeras direkt och vad som är en förklaring.",
    ],
    "Beskriv tre vardagshändelser. Alla visar processord och riktning mellan formerna på miniwhiteboard.",
    "Om avdunstning beskrivs som försvinnande, samla vattenånga som droppar på ett kallt lock. Om processerna skiljs, lägg till kondensation.",
    "Efter några dagar förklarar eleverna en vattenpöl som minskar och frost som bildas med rätt processord.",
  ),
  "kemi-4-6-1": p(
    "Eleverna ritar partiklar större i gas och mindre i fast form eller tror att partiklarna försvinner när ämnet avdunstar.",
    [6, 8, 5, 9],
    [
      "Visa tre partikelbilder med samma antal och storlek på partiklar men olika avstånd och ordning. Koppla dem till is, vatten och vattenånga.",
      "Modellera vad modellen visar och inte visar: partiklar, avstånd och rörelse – inte realistisk färg eller faktisk skala.",
      "Eleverna rättar bilder där partiklarna växer, krymper eller försvinner och förklarar varje ändring.",
      "De ritar före–efter för smältning och avdunstning med oförändrat antal partiklar i en sluten behållare.",
    ],
    "Visa fyra partikelbilder. Eleverna väljer tillstånd och skriver vilket synligt kännetecken i modellen som avgör valet.",
    "Om partikelstorlek ändras, håll en utskuren partikelmall konstant mellan bilder. Om modellen förstås, koppla rörelse till temperatur utan att säga att partiklar innehåller värme.",
    "Nästa vecka ritar eleverna en partikelmodell för kondensation utan stödlinjer.",
  ),
  "kemi-4-6-2": p(
    "Eleverna kallar saltvatten en kemisk reaktion eftersom saltet inte syns och kallar grumligt vatten en lösning trots synliga partiklar.",
    [6, 5, 7, 9],
    [
      "Jämför sand i vatten, salt i vatten och bikarbonat med vinäger. Lista observationer före, under och efter utan att dra slutsats först.",
      "Modellera begreppen blandning, lösning och kemisk förändring med kriterier: jämn fördelning, möjlighet att separera och tecken på nya ämnen.",
      "Eleverna placerar fallen i en jämförelsetabell och föreslår filtrering eller avdunstning som test där det passar.",
      "Ge nya fall som sockerlösning, olja och vatten samt rostande järn. Eleverna klassificerar och anger vilket belägg som saknas för säker slutsats.",
    ],
    "Visa ett okänt genomskinligt prov. Eleverna får inte bara kalla det lösning utan skriver vilket test eller vilken bakgrundsinformation som behövs.",
    "Om osynligt tolkas som borta eller reagerat, avdunsta en saltlösning. Om kriterierna används, diskutera att observationer ibland inte ensamma avgör kemisk förändring.",
    "Senare klassificerar eleverna nya vardagsfall och motiverar med kriterier utan tabellen.",
  ),
  "kemi-7-9-1": p(
    "Eleverna blandar ihop atom, jon och molekyl när samma grundämnessymbol förekommer och läser index eller laddning som antal separata ämnen.",
    [6, 8, 5, 9],
    [
      "Visa partikelbild och symbol sida vid sida för He, O₂, H₂O, Na⁺ och SO₄²⁻. Markera atomslag, antal atomer och nettoladdning separat.",
      "Modellera en beslutstrappa: en eller flera atomkärnor, samma eller olika atomslag och neutral eller laddad partikel.",
      "Eleverna sorterar tolv kort och måste para varje symbol med rätt partikelbild. Lägg in Na och Na⁺ som närliggande kontrast.",
      "De ritar egna partikelbilder för CO₂, Cl⁻ och NH₄⁺ och skriver kategori plus motivering.",
    ],
    "Ge fyra nya symboler. Eleverna klassificerar varje och markerar exakt vilken del av notation som visar antal respektive laddning.",
    "Om laddning läses som antal, jämför placeringen av index och exponent. Om klassificeringen är säker, lägg till jonförening och skilj formelenhet från molekyl.",
    "Efter en vecka återkallar eleverna beslutstrappan och använder den på nya symboler.",
  ),
  "kemi-7-9-2": p(
    "Eleverna balanserar reaktionsformler genom att ändra index i ämnena och ser inte att atomer omgrupperas men bevaras.",
    [6, 8, 7, 9],
    [
      "Bygg H₂ + O₂ → H₂O med färgade atombrickor. Räkna varje atomslag på båda sidor innan koefficienter sätts ut.",
      "Modellera varför koefficienten får ändras men index inte: index beskriver ämnets partiklar, koefficienten antalet partiklar.",
      "Eleverna balanserar med brickor och översätter varje uppställning till symbolisk form. Ett felaktigt indexbyte används som icke-exempel.",
      "De balanserar Fe + O₂ → Fe₂O₃ och kontrollerar med en atomtabell i stället för att följa en blind regel.",
    ],
    "Visa två påstådda balanseringar. Eleverna väljer den giltiga, räknar atomer och förklarar varför den andra beskriver andra ämnen.",
    "Om index ändras, återgå till partikelmodellen. Om atomer räknas säkert, ta bort brickorna och öka komplexiteten stegvis.",
    "Nästa vecka balanserar eleverna nya reaktioner och ritar en av dem på partikelnivå som kontroll.",
  ),
  "kemi-gymnasiet-1": p(
    "Eleverna kan utföra substansmängdsberäkningar men kopplar inte färgförändring i bägaren till omgruppering av partiklar och den balanserade reaktionsformeln.",
    [3, 8, 7, 9],
    [
      "Använd en kort film eller demonstration av kopparjoner och hydroxidjoner som bildar fällning. Dela tavlan i makro-, partikel- och symbolnivå.",
      "Modellera samma ögonblick på alla tre nivåer och peka ut vad varje representation tillför. Ta bort åskådarjoner först efter att helheten visats.",
      "Eleverna får en halvfärdig tredelad tabell och kompletterar partikelbild samt nettojonformel från observationen.",
      "Ge en ny utfällningsreaktion. Eleverna beskriver observation, ritar partiklar före–efter och skriver balanserad formel med tillståndsbeteckningar.",
    ],
    "Visa endast en partikelbild efter blandning. Eleverna härleder möjlig observation och nettojonformel samt anger vad bilden inte avslöjar.",
    "Om nivåerna blandas i samma mening, låt eleven märka varje påstående M, P eller S. Om kopplingarna håller, lägg till kvantitativ substansmängd.",
    "Senare översätter eleverna en ny reaktion mellan nivåerna utan den tredelade tavlan.",
  ),
  "kemi-gymnasiet-2": p(
    "Eleverna säger att jämvikten ”flyttas åt höger” som en regel men förklarar inte hur framåt- och bakåtreaktionens hastigheter förändras efter störningen.",
    [6, 7, 9, 10],
    [
      "Visa koncentration–tid-grafer för ett system i dynamisk jämvikt. Markera att konstanta koncentrationer inte betyder att reaktionerna har stannat.",
      "Modellera tillsats av reaktant i tre steg: omedelbar koncentrationsändring, ändrade reaktionshastigheter och ny jämvikt när hastigheterna åter är lika.",
      "Eleverna kompletterar grafer för tillsats, borttagning och volymändring och skriver vad som händer omedelbart respektive över tid.",
      "Ge N₂O₄ ⇌ 2NO₂ med färginformation. Eleverna förutsäger synlig förändring och förklarar den med hastigheter och koncentrationer.",
    ],
    "Ge en störning utan färdig reaktionspil. Eleverna ritar kvalitativa hastighetskurvor och anger när ny jämvikt råder.",
    "Om svaret bara citerar Le Chateliers princip, fråga vilken reaktionshastighet som ändras först och varför. Om mekanismen håller, jämför med katalysator som inte ändrar jämviktsläget.",
    "En vecka senare analyserar eleverna ett nytt jämviktssystem utan de färdiga tre stegen.",
  ),

  "historia-f-3-1": p(
    "Eleverna känner igen bilderna av en skolstart, en utflykt och en födelsedag men blandar ihop ordning och hur lång tid som gått mellan händelserna.",
    [6, 8, 4, 9],
    [
      "Använd fyra daterade fotografier från ett påhittat barns år. Läs datum och placera först bara start och slut på en golvtidslinje.",
      "Modellera orden före, efter och samtidigt samt visa att avståndet på linjen ska motsvara ungefär hur mycket tid som gått.",
      "Eleverna placerar de två återstående korten, motiverar placeringen och rättar en tidslinje där november ligger före september.",
      "Ge nya kort från en skoldag. Eleverna ordnar dem och skriver två meningar med före och efter.",
    ],
    "Dölj linjen och låt eleverna ordna tre händelser samt svara vilken som ligger närmast en angiven händelse i tid.",
    "Om ordningen är rätt men avstånden slumpmässiga, jämför datumparen konkret. Om båda fungerar, lägg in två samtidiga händelser på olika platser.",
    "Några dagar senare bygger eleverna en tidslinje ur en kort muntlig berättelse utan bilder.",
  ),
  "historia-f-3-2": p(
    "Eleverna beskriver ett gammalt fotografi som ”förr” men skiljer inte sådant som förändrats från sådant som fortfarande fyller samma funktion.",
    [6, 7, 9, 10],
    [
      "Visa ett daterat klassrumsfoto och ett nutida foto. Ange vad källorna är och att ett fotografi visar ett valt ögonblick, inte allt skolliv.",
      "Modellera en jämförelse: konkret iakttagelse, likhet eller skillnad och försiktig slutsats om exempelvis möbler eller arbetsform.",
      "Eleverna fyller två kolumner, förändring och kontinuitet, med belägg som faktiskt syns i bilderna.",
      "Lägg till ett kort utdrag ur en skolregel från tiden. Eleverna reviderar eller preciserar en slutsats från fotografiet.",
    ],
    "Eleverna skriver en förändring och en kontinuitet med formuleringen ”Jag ser … därför kan jag säga …”.",
    "Om de gissar om människors känslor, skilj iakttagelse från tolkning. Om beläggen används väl, fråga vad bilderna inte kan berätta.",
    "Nästa vecka jämför eleverna två nya källor om lek eller boende utan den färdiga tabellen.",
  ),
  "historia-4-6-1": p(
    "Eleverna radar upp ångmaskin, fabriker och urbanisering men visar inte vilket samband som gör den ena förändringen till orsak eller konsekvens.",
    [6, 8, 7, 9],
    [
      "Ge sex kort om industrialiseringen: jordbruksförändringar, arbetskraft, ångkraft, fabriker, städer och arbetsvillkor. Låt eleverna först sortera bakgrund, förändring och följd.",
      "Modellera en pil mellan två kort och skriv mekanismen ovanför: ”ökad produktivitet frigjorde arbetskraft”.",
      "Eleverna bygger två möjliga orsakskedjor och måste skriva en verbfras på varje pil; en pil utan förklaring godkänns inte.",
      "De jämför kedjorna och anger om en faktor kan vara både konsekvens i ett led och orsak i nästa.",
    ],
    "Ta bort korten. Eleverna skriver två orsaker till urbanisering och förklarar var sin mekanism samt en konsekvens.",
    "Om sambandet uttrycks som ”ledde till” utan hur, ställ följdfrågan ”genom vilken förändring?”. Om kedjorna håller, lägg till att historiska följder kan återverka på orsaker.",
    "En vecka senare använder eleverna samma orsaksstruktur på en annan historisk förändring.",
  ),
  "historia-4-6-2": p(
    "Eleverna återberättar vad en källa säger men drar slutsatser om hela epoken från ett enskilt brev eller föremål.",
    [6, 9, 10, 7],
    [
      "Välj ett kort emigrantbrev och formulera frågan ”Vad kan brevet säga om just skribentens skäl att resa?”. Ange avsändare, mottagare och datum.",
      "Modellera en källnära slutsats med citat och avgränsning: brevet visar vad skribenten uppger, inte automatiskt alla emigranters motiv.",
      "Eleverna markerar två belägg och väljer mellan tre slutsatser: för stark, irrelevant och rimligt avgränsad.",
      "Lägg till statistik över emigranters ursprungsregioner. Eleverna beskriver vad den nya källan kan komplettera men inte ersätta.",
    ],
    "Eleverna skriver ”Källan kan användas för att … eftersom … men den visar inte …”. Kontrollera att varje led kopplas till den bestämda frågan.",
    "Om slutsatsen generaliserar till alla, minska den till skribenten eller källgruppen. Om den är väl avgränsad, låt eleverna kombinera två källor.",
    "Senare får eleverna en ny historisk fråga och väljer vilken av två källor som är mest användbar.",
  ),
  "historia-7-9-1": p(
    "Eleverna nämner samma allmänna orsaker till två revolutioner men skiljer inte långsiktiga strukturer från utlösande händelser.",
    [6, 5, 8, 9],
    [
      "Bygg en matris för franska och ryska revolutionen med ekonomi, politisk makt, social ordning och utlösande händelse.",
      "Modellera skillnaden mellan ett långvarigt villkor och det som förändrar situationen just då. Placera ett exempel och motivera kategorin.",
      "Eleverna placerar källbelagda orsaker i matrisen och skriver en mekanism för två samband, inte bara en etikett.",
      "De formulerar en jämförelse som anger både likhet och skillnad samt hur skillnaden påverkade förloppet.",
    ],
    "Ge fyra orsaker utan rubriker. Eleverna sorterar dem för båda revolutionerna och skriver vilken som bäst förklarar tidpunkten.",
    "Om allt kallas orsak på samma nivå, återgå till villkor kontra utlösare. Om nivåerna skiljs, låt eleverna väga betydelse med ett motargument.",
    "Vid nästa arbetsområde jämför eleverna orsaksstrukturer utan den färdiga matrisen.",
  ),
  "historia-7-9-2": p(
    "Eleverna bedömer en källa som trovärdig eller partisk i allmänhet utan att koppla bedömningen till den historiska frågan.",
    [2, 6, 9, 10],
    [
      "Använd en värvningsaffisch och ställ två frågor: vad staten ville kommunicera och hur soldater faktiskt upplevde fronten.",
      "Modellera hur samma tendentiösa källa kan vara mycket användbar för den första frågan men svag för den andra.",
      "Eleverna granskar avsändare, tid, beroende och syfte och skriver vad varje uppgift gör möjligt att undersöka.",
      "Lägg till ett soldatbrev. Eleverna jämför källornas användbarhet för en exakt fråga utan att utse en källa till alltid bäst.",
    ],
    "Ge en ny fråga om propagandaaffischens publik. Eleverna skriver ett användbarhetsomdöme med belägg och begränsning.",
    "Om svaret bara säger partisk, fråga ”Användbar för vad?”. Om frågekopplingen är tydlig, pröva hur ett beroendeförhållande ändrar bedömningen.",
    "En vecka senare bedömer eleverna en ny källa för två olika frågor.",
  ),
  "historia-gymnasiet-1": p(
    "Eleverna producerar en lång orsakslista men rangordnar inte förklaringarna eller visar hur aktörers beslut verkade inom strukturella villkor.",
    [6, 7, 9, 10],
    [
      "Avgränsa utfallet, exempelvis varför Berlinmuren öppnades i november 1989. Ge en tidslinje och fyra korta källutdrag.",
      "Modellera en förklaringskarta med strukturellt villkor, aktörsbeslut, utlösande händelse och mekanism fram till utfallet.",
      "Eleverna bygger två konkurrerande förklaringar och anger vilket källbelägg som stöder varje länk.",
      "De skriver en rangordnad slutsats och prövar den mot ett kontrafaktiskt: vilket utfall blir mindre sannolikt om en faktor tas bort?",
    ],
    "Eleverna lämnar den starkaste förklaringen, en mekanism, ett belägg och en rimlig alternativ förklaring. Antalet nämnda orsaker bedöms inte.",
    "Om rangordningen bygger på åsikt, kräv jämförelsekriterium som tidsnärhet eller förklarad mekanism. Om den håller, undersök källornas begränsningar.",
    "Senare analyserar eleverna ett annat avgränsat utfall och konstruerar kategorierna själva.",
  ),
  "historia-gymnasiet-2": p(
    "Eleverna identifierar att historia används i en film eller ett tal men förklarar inte urvalet, syftet eller den samtida mottagaren.",
    [6, 9, 10, 5],
    [
      "Välj ett konkret minnestal eller en reklam där en historisk händelse används. Jämför utdraget med en kort sakframställning av händelsen.",
      "Modellera fyra frågor: vad väljs ut, vad utelämnas, vilket nutida syfte tjänar urvalet och vilken publik adresseras?",
      "Eleverna markerar två historiska referenser och kopplar varje till en möjlig funktion, exempelvis legitimering, identitet eller kritik.",
      "De jämför ett andra bruk av samma historia och förklarar varför olika sammanhang ger olika urval.",
    ],
    "Eleverna skriver en analyskedja historisk referens → urval → nutida budskap → avsedd funktion och anger ett text- eller bildbelägg.",
    "Om syftet bara gissas, be om stöd i formulering, avsändare och situation. Om kedjan är underbyggd, pröva en alternativ mottagartolkning.",
    "Vid nästa tillfälle analyserar eleverna ett nytt historiebruk utan frågemallen.",
  ),

  "samhällskunskap-f-3-1": p(
    "Eleverna kallar varje omröstning demokratisk och ser inte skillnaden mellan att få rösta, få information och ha en gemensamt bestämd beslutsregel.",
    [6, 5, 9, 10],
    [
      "Spela upp tre korta klassrumssituationer: läraren bestämmer bok, en elev bestämmer åt alla och klassen röstar mellan två möjliga böcker efter samtal.",
      "Modellera jämförelsen med frågorna vem får föreslå, vem får uttrycka sin mening, hur fattas beslutet och gäller regeln lika?",
      "Eleverna sorterar nya situationer som ensidigt eller gemensamt beslut och pekar ut exakt vilket steg som avgör.",
      "Klassen fattar ett verkligt, begränsat beslut om högläsningsordning med kända alternativ och i förväg bestämd regel.",
    ],
    "Ge en situation där alla röstar men bara ett alternativ tillåts. Eleverna svarar vad som är demokratiskt i processen och vad som saknas.",
    "Om omröstning ensam blir kriteriet, jämför med den begränsade situationen. Om processen förstås, diskutera varför vissa beslut inte kan tas med enkel majoritet.",
    "Nästa vecka förklarar eleverna ett nytt beslut med de fyra frågorna utan stödkort.",
  ),
  "samhällskunskap-f-3-2": p(
    "Eleverna kan namnge bibliotek eller räddningstjänst men beskriver inte vilket gemensamt behov verksamheten möter eller hur människor får hjälp.",
    [6, 7, 9, 1],
    [
      "Välj biblioteket. Visa en enkel bildkedja från gemensamma resurser till lokaler, personal, lån och invånare som använder tjänsten.",
      "Modellera skillnaden mellan byggnaden och funktionen: bibliotekets uppgift kan vara tillgång till böcker, information och plats även när individen inte äger allt.",
      "Eleverna får kort om brand, sjukdom, avfall och läsning och parar behov med räddningstjänst, vård, sophämtning och bibliotek.",
      "De väljer en funktion och ritar vad som skulle bli svårare för olika människor om den saknades en vecka.",
    ],
    "Varje elev förklarar en funktion med mallen behov → verksamhetens handling → vem som får hjälp. Namnet på verksamheten räcker inte.",
    "Om svaret blir ”den är bra”, fråga vilket konkret problem den löser. Om kedjan håller, jämför offentlig verksamhet med privat tjänst utan att värdera förenklat.",
    "Senare återkallar eleverna kedjan och använder den på en ny samhällsfunktion.",
  ),
  "samhällskunskap-4-6-1": p(
    "Eleverna kallar önskemål rättigheter och tolkar skyldighet som vad en vuxen råkar säga åt dem att göra.",
    [6, 5, 7, 9],
    [
      "Ge åtta konkreta påståenden, exempelvis rätt till utbildning, önskan om ny mobil och skolplikt. Ange vilken regel eller överenskommelse exemplen bygger på.",
      "Modellera kriterierna rättighetsbärare, ansvarig part och regelgrund. Skilj juridisk skyldighet från vardaglig uppgift.",
      "Eleverna sorterar korten i rättighet, skyldighet eller önskemål och skriver kriteriet vid två gränsfall.",
      "De kopplar en rättighet till vem som har ansvar att möjliggöra den och diskuterar om samma person kan ha både rättighet och skyldighet.",
    ],
    "Visa tre nya fall. Eleverna klassificerar och hänvisar till ett kriterium; vardaglig känsla av rättvisa räcker inte som motivering.",
    "Om allt viktigt kallas rättighet, återgå till regelgrund och ansvarig part. Om klassificeringen fungerar, lägg till fall där rättigheter behöver vägas mot varandra.",
    "Nästa vecka klassificerar eleverna exempel ur en kort nyhetstext utan sorteringsrubriker.",
  ),
  "samhällskunskap-4-6-2": p(
    "Eleverna beskriver köp som en linje från butik till kund och missar arbete, betalningar, skatter och offentliga tjänster mellan aktörerna.",
    [3, 8, 6, 9],
    [
      "Följ en liter mjölk. Placera hushåll, mejeri, butik och kommun i en enkel karta och lägg till endast ett flöde i taget.",
      "Modellera varuflöde, arbete och penningflöde med olika piltyper. Visa att skatt inte är en vara och lön inte går åt samma håll som arbete.",
      "Eleverna får pilkort och rättar en karta där lön, mjölk och skatt har blandats ihop.",
      "De lägger till en offentlig tjänst, exempelvis väg eller skola, och förklarar två indirekta samband med varans väg.",
    ],
    "Ge en halvfärdig karta. Eleverna fyller tre pilar och namnger både det som flödar och riktningen.",
    "Om alla pilar kallas pengar, återinför färgerna för vara, arbete och betalning. Om kartan fungerar, lägg till bank eller import som en ny aktör.",
    "Efter några dagar bygger eleverna en motsvarande karta för en tröja utan den färdiga layouten.",
  ),
  "samhällskunskap-7-9-1": p(
    "Eleverna återger etiketter som liberal eller socialistisk men härleder inte hur olika värden leder till olika svar på samma sakfråga.",
    [6, 5, 7, 9],
    [
      "Välj en avgränsad fråga, exempelvis vinst i skolan. Ge två korta, representativa argument med tydlig avsändare och sammanhang.",
      "Modellera kedjan grundvärde → problemdefinition → föreslagen åtgärd → möjlig målkonflikt utan att framställa perspektiv som enhetliga paket.",
      "Eleverna markerar värde och åtgärd i argumenten och jämför hur samma faktauppgift kan få olika politisk betydelse.",
      "De skriver två möjliga svar på ett nytt fall ur var sitt perspektiv och anger variation eller oenighet inom perspektivet.",
    ],
    "Eleverna får ett nytt förslag och förklarar vilket grundvärde som kan stödja det samt ett skäl till att etiketten ändå är osäker.",
    "Om svaren blir stereotyper, återgå till de faktiska argumenten och avsändarna. Om kedjan håller, lägg till ett tredje perspektiv eller en målkonflikt.",
    "Senare analyserar eleverna partiers verkliga formuleringar utan färdiga perspektivnamn.",
  ),
  "samhällskunskap-7-9-2": p(
    "Eleverna kallar alla sifferpåståenden fakta och alla värdeladdade meningar åsikter, även när en kausal förklaring behöver belägg.",
    [6, 5, 9, 10],
    [
      "Skriv tre meningar om arbetslöshet: ett verifierbart sakpåstående, en värdering och en förklaring till förändring.",
      "Modellera kriterierna: fakta kan kontrolleras, värdering uttrycker hur något bör bedömas och förklaring påstår varför något händer.",
      "Eleverna sorterar tolv meningar och markerar vilket ord eller vilken struktur som avgör. Lägg in en felaktig faktauppgift som fortfarande är ett sakpåstående.",
      "De skriver om samma samhällsfråga med en mening av varje typ och anger vilket belägg en förklaring skulle kräva.",
    ],
    "Visa påståendet ”Arbetslösheten steg på grund av skatten”. Eleverna klassificerar delarna och skriver vilken jämförelse eller data som behövs för orsaksledet.",
    "Om sant blandas ihop med påståendetyp, använd ett falskt men kontrollerbart sakpåstående. Om typerna skiljs, analysera meningar som innehåller flera typer samtidigt.",
    "En vecka senare klassificerar eleverna påståenden ur en nyhetsartikel och motiverar utan listan över kriterier.",
  ),
  "samhällskunskap-gymnasiet-1": p(
    "Eleverna tolkar ett samband mellan skärmtid och sömn som att skärmtid orsakar sämre sömn utan att granska urval, mätning eller tredje variabler.",
    [2, 9, 10, 6],
    [
      "Ge en kort resultattext med korrelation, urvalsstorlek och hur variablerna mättes. Låt eleverna skilja det observerade resultatet från rubrikens orsakspåstående.",
      "Modellera ett kausalt diagram med skärmtid, sömn, stress och ålder och visa två alternativa förklaringar: omvänd kausalitet och gemensam orsak.",
      "Eleverna granskar urval, självrapportering och bortfall och anger vilken typ av slutsats varje begränsning påverkar.",
      "De skriver en ny rubrik och slutsats vars styrka motsvarar studiens design samt föreslår en mätning som skulle minska en osäkerhet.",
    ],
    "Eleverna lämnar observerat samband, två alternativa förklaringar och en avgränsad slutsats. Orden påverkar eller leder till kräver särskilt stöd.",
    "Om korrelation fortfarande blir orsak, jämför med ett omvänt samband. Om granskningen är god, diskutera vilka etiska och praktiska gränser ett experiment skulle ha.",
    "Senare granskar eleverna ett nytt påstående utan den färdiga checklistan och återkallar själva de viktigaste hoten mot slutsatsen.",
  ),
  "samhällskunskap-gymnasiet-2": p(
    "Eleverna säger att en räntehöjning är bra eller dålig i allmänhet och följer inte olika effekter för inflation, arbetslöshet, låntagare och sparare.",
    [6, 7, 9, 10],
    [
      "Ge ett förenklat läge med hög inflation, svag tillväxt och hushåll med olika skuldsättning. Definiera målen innan åtgärder bedöms.",
      "Modellera en orsakskedja från höjd styrränta via lånekostnad och efterfrågan till möjlig inflationseffekt och markera tidsfördröjning.",
      "Eleverna bygger motsvarande kedja för finanspolitisk åtstramning och markerar vilka grupper som påverkas direkt respektive indirekt.",
      "De jämför åtgärderna mot tre kriterier: måluppfyllelse, fördelning och risk eller osäkerhet. Ett enda slutomdöme tillåts inte före jämförelsen.",
    ],
    "Eleverna rekommenderar en åtgärd för det givna läget och måste ange mekanism, målkonflikt, vinnare eller förlorare och ett antagande.",
    "Om svaret bara följer politisk etikett, återgå till mekanismen. Om kedjan håller, ändra ett villkor i scenariot och kontrollera om rekommendationen revideras.",
    "Vid nästa fall väljer eleverna själva relevanta mål och jämförelsekriterier utan tabellen.",
  ),

  "geografi-f-3-1": p(
    "Eleverna följer en ritad väg men använder inte kartans symboler, väderstreck eller lägesord när de beskriver den för någon annan.",
    [6, 8, 7, 9],
    [
      "Använd en enkel karta över ett påhittat område med skola, bro, park och bibliotek. Gå igenom teckenförklaringen före vägbeskrivningen.",
      "Modellera en rutt från skolan till parken med norrpil och orden norrut, förbi, över och mellan. Peka samtidigt på varje kartdel.",
      "Eleverna följer tre beskrivningar och väljer rätt mål. En beskrivning innehåller ett fel som de ska hitta och rätta.",
      "I par beskriver en elev en ny väg utan att peka; den andra ritar rutten och jämför sedan med originalet.",
    ],
    "Ge start och mål. Eleverna skriver tre steg med minst ett väderstreck och två landmärken så att en annan elev kan följa rutten.",
    "Om beskrivningen bara säger höger och vänster, vrid kartan och återgå till väderstreck. Om den fungerar, lägg till alternativ rutt och jämför längd.",
    "Nästa vecka beskriver eleverna en ny karta utan ordlistan.",
  ),
  "geografi-f-3-2": p(
    "Eleverna säger att två platser är olika för att den ena är finare eller större men använder inte natur, bebyggelse och markanvändning som jämförelsepunkter.",
    [6, 8, 5, 9],
    [
      "Visa ett flygfoto av en kustby och en stadsdel. Dela tavlan i natur, byggnader och vad människor använder platsen till.",
      "Modellera en jämförelse med samma dimension på båda platserna: kust och hamn jämfört med hårdgjord mark och vägar.",
      "Eleverna placerar bilddetaljer i rätt kolumn och skiljer iakttagelsen ”många bryggor” från tolkningen ”fiske eller båtliv”.",
      "De skriver två likheter eller skillnader och en försiktig förklaring till hur en naturförutsättning kan påverka användningen.",
    ],
    "Visa två nya utsnitt. Eleverna ger en jämförelse där båda platserna och samma dimension nämns.",
    "Om svaren blir värdeord, be om det synliga belägget. Om jämförelsen är konkret, fråga vilka uppgifter som behövs för att veta mer om människors liv.",
    "Senare jämför eleverna sin närmiljö med en ny plats utan den färdiga tabellen.",
  ),
  "geografi-4-6-1": p(
    "Eleverna hittar orter på kartan men använder inte skala, teckenförklaring och höjdkurvor för att dra slutsatser om avstånd eller terräng.",
    [6, 8, 7, 9],
    [
      "Välj en topografisk karta med två möjliga vandringsleder. Markera start, mål, skala och höjdkurvornas ekvidistans.",
      "Modellera hur kartavstånd omvandlas till verkligt avstånd och hur täta höjdkurvor visar brantare terräng.",
      "Eleverna mäter båda lederna, räknar verklig längd och markerar den brantaste sträckan. De rättar en slutsats som bara bygger på kortast linje.",
      "De rekommenderar led för en barnfamilj respektive en tränad löpare och använder minst två kartbelägg.",
    ],
    "Ge ett nytt kartutsnitt. Eleverna anger verkligt avstånd och väljer vilken sida av höjden som är brantast med motivering.",
    "Om skala och höjd blandas, dela kontrollen i två steg. Om avläsningen fungerar, lägg till att kartan inte visar aktuellt väglag.",
    "Nästa vecka löser eleverna ett nytt ruttproblem utan den markerade skalan och höjdkurvan.",
  ),
  "geografi-4-6-2": p(
    "Eleverna kan rita ett cirkulärt kretslopp men kopplar inte nederbörd och avrinning till höjd, markyta och människors uttag av vatten.",
    [6, 8, 7, 9],
    [
      "Använd en karta med berg, skog, stad, sjö och hav. Lägg processkorten avdunstning, kondensation, nederbörd, infiltration och avrinning på rätt plats.",
      "Modellera en vattendroppes väg från regn på berget till grundvatten eller flod och markera var marktyp kan ändra vägen.",
      "Eleverna jämför skog och asfalterad stadsyta och förutsäger infiltration och snabb avrinning med samma mängd regn.",
      "Lägg till dricksvattenuttag. Eleverna förklarar hur användningen kopplar samhälle till det fysiska kretsloppet.",
    ],
    "Ge ett skyfall över två markytor. Eleverna ritar två vattenvägar och motiverar skillnaden med infiltration och avrinning.",
    "Om kretsloppet bara blir pilar i en cirkel, knyt varje process till kartans plats. Om modellen håller, diskutera förorening eller torka.",
    "Senare förklarar eleverna en översvämningsrisk i ett nytt landskap utan processkorten.",
  ),
  "geografi-7-9-1": p(
    "Eleverna förklarar hög befolkningstäthet med klimat ensam och bortser från arbete, infrastruktur, historia och politiska beslut.",
    [6, 8, 9, 10],
    [
      "Jämför två regionkartor med befolkning, topografi, transportnät och större näringar. Beskriv först mönstret utan orsaksspråk.",
      "Modellera en flerfaktorsförklaring där flodläge möjliggör odling och transport men där industrialisering och infrastruktur förstärker koncentrationen.",
      "Eleverna markerar vilket kartlager som stöder varje påstående och formulerar en alternativ förklaring till samma mönster.",
      "Ge ett kontrastfall där gynnsamt klimat inte ger hög täthet. Eleverna reviderar en enkelfaktorsförklaring.",
    ],
    "Eleverna förklarar ett valt täthetsmönster med en naturgiven och en samhällelig faktor samt mekanismen mellan faktor och bosättning.",
    "Om faktorer bara listas, kräv ett därför-led. Om mekanismerna håller, fråga vilket ytterligare dataunderlag som skulle pröva förklaringen.",
    "Nästa vecka analyserar eleverna ett nytt område utan färdig lista över faktorer.",
  ),
  "geografi-7-9-2": p(
    "Eleverna väljer sida i en markkonflikt men kartlägger inte aktörernas intressen, makt eller konsekvenser på kort och lång sikt.",
    [6, 7, 9, 10],
    [
      "Använd ett avgränsat fall om gruva, vindpark eller skogsbruk med karta och korta källor från boende, företag, kommun och miljöorganisation.",
      "Modellera en aktörstabell med mål, belägg, möjlig vinst, kostnad och beslutsmakt. Skilj aktörens påstående från lärarens bedömning.",
      "Eleverna fyller tabellen och markerar en konsekvens som byter värdering beroende på tidsskala eller geografisk skala.",
      "De formulerar två handlingsalternativ och jämför dem med samma kriterier i stället för att bara argumentera för favoriten.",
    ],
    "Eleverna rekommenderar ett alternativ med två belägg, en erkänd nackdel och en aktör som påverkas annorlunda.",
    "Om perspektiven blir karikatyrer, återgå till aktörernas faktiska källor. Om avvägningen är tydlig, pröva hur ny information ändrar beslutet.",
    "Senare analyserar eleverna en ny intressekonflikt och väljer själva relevanta aktörer och kriterier.",
  ),
  "geografi-gymnasiet-1": p(
    "Eleverna beskriver jordbävningens magnitud som katastrofens storlek och skiljer inte naturhändelse, exponering, sårbarhet och beredskap.",
    [6, 8, 9, 10],
    [
      "Jämför två jordbävningar med liknande magnitud men olika dödstal och skador. Ge data om byggnader, befolkningstäthet, tidpunkt och räddningskapacitet.",
      "Modellera riskkedjan naturhändelse → exponering → sårbarhet → konsekvens och placera beredskap som faktor som kan minska skadan.",
      "Eleverna kopplar varje datapunkt till rätt del och formulerar två konkurrerande förklaringar till skillnaden i konsekvens.",
      "De föreslår en åtgärd och anger exakt vilken länk i kedjan den påverkar samt vilken grupp den når.",
    ],
    "Ge ett tredje fall. Eleverna bedömer sårbarhet med minst tre indikatorer och skiljer vad data visar från vad som behöver antas.",
    "Om magnitud ensam används, håll händelsen konstant och variera exponering. Om modellen håller, diskutera hur indikatorval påverkar jämförelsen.",
    "Vid nästa naturhändelse rekonstruerar eleverna riskkedjan utan den förtryckta modellen.",
  ),
  "geografi-gymnasiet-2": p(
    "Eleverna kallar en strategi hållbar när den minskar utsläpp men prövar inte ekonomiska, sociala eller geografiskt förskjutna konsekvenser.",
    [2, 9, 10, 6],
    [
      "Avgränsa en strategi, exempelvis elektrifierad biltrafik. Ange mål, tidshorisont och jämförelsealternativ innan bedömningen börjar.",
      "Modellera en konsekvensmatris med ekologisk, ekonomisk och social dimension samt lokal, nationell och global skala.",
      "Eleverna placerar belägg om utsläpp, mineralutvinning, kostnad och tillgänglighet i matrisen och skiljer livscykel från driftfas.",
      "De väger strategin mot ett alternativ med samma kriterier och anger vilken värdering som styr den slutliga prioriteringen.",
    ],
    "Eleverna skriver en villkorad bedömning: strategin bidrar till vilket mål, under vilka antaganden, med vilken nackdel och för vilken grupp eller skala.",
    "Om svaret bara säger hållbart eller ohållbart, kräv kriterium och jämförelse. Om avvägningen håller, ändra tidshorisont eller systemgräns.",
    "Senare bedömer eleverna en ny strategi och konstruerar själva matrisens relevanta rader.",
  ),

  "religionskunskap-f-3-1": p(
    "Eleverna säger att ”alla firar likadant” efter att ha sett ett exempel och blandar ihop högtidens berättelse med en familjs sätt att fira.",
    [6, 5, 9, 10],
    [
      "Använd två korta, namngivna familjeberättelser om exempelvis jul och eid och ange att de är exempel, inte regler för alla.",
      "Modellera tre jämförelsepunkter: varför högtiden uppmärksammas, vad just familjen gör och vilken variation berättelsen nämner.",
      "Eleverna placerar uppgifter i ett Venndiagram men märker dem ”den här familjen” när källan bara gäller ett fall.",
      "Lägg till ett andra exempel från samma tradition. Eleverna reviderar en mening som tidigare generaliserade.",
    ],
    "Eleverna skriver en likhet, en skillnad och en mening som uttryckligen visar att människor inom samma tradition kan göra olika.",
    "Om alla-formuleringar finns kvar, fråga vilket underlag som skulle krävas för ordet alla. Om variationen förstås, jämför högtidens betydelse och praktik.",
    "Nästa vecka jämför eleverna två nya exempel utan det färdiga Venndiagrammet.",
  ),
  "religionskunskap-f-3-2": p(
    "Eleverna säger sin egen uppfattning om en livsfråga men återger en klasskamrats perspektiv förenklat eller som om de höll med.",
    [7, 9, 6, 1],
    [
      "Välj frågan ”Vad gör en bra vän?”. Modellera två olika rimliga svar och skilj att förstå ett perspektiv från att själv dela det.",
      "Tänk högt när du återger: ”Jag hör att du menar … eftersom … Har jag förstått rätt?”.",
      "Eleverna väljer mellan fyra återgivningar av samma svar och identifierar vilken som lägger till något talaren inte sa.",
      "I par ger den ena ett skäl. Den andra återger skälet och får en ja- eller nej-kontroll innan den uttrycker sitt eget perspektiv.",
    ],
    "Lyssna efter om återgivningen innehåller både ståndpunkt och skäl utan värderande tillägg. Låt varje elev skriva ett eget och ett korrekt återgivet annat perspektiv.",
    "Om återgivningen blir ett motargument, modellera lyssningssteget igen. Om den är rättvis, lägg till en följdfråga som söker förtydligande.",
    "Senare använder eleverna samma samtalsstruktur om en ny livsfråga utan meningsstarten.",
  ),
  "religionskunskap-4-6-1": p(
    "Eleverna kallar alla religiösa föremål symboler och ser inte skillnaden mellan ett tecken, en handling som upprepas och en berättelse som ger mening.",
    [6, 5, 8, 9],
    [
      "Välj ett tydligt exempel där symbol, ritual och berättelse hör samman, exempelvis nattvardens bröd och vin, handlingen och berättelsen bakom.",
      "Modellera definitionerna med funktion: symbol bär betydelse, ritual är en återkommande meningsfull handling och berättelse ordnar händelser och mening.",
      "Eleverna sorterar konkreta exempel och icke-exempel och förklarar gränsfall där samma föremål kan ha olika funktion i olika sammanhang.",
      "De ritar en triangel mellan ett nytt symbolspråk, en praktik och en berättelse och skriver vad varje länk betyder.",
    ],
    "Ge tre nya exempel från angivet sammanhang. Eleverna klassificerar funktionen och motiverar; föremålets utseende räcker inte.",
    "Om allt synligt blir symbol, fråga vilken betydelse det bär i källan. Om begreppen skiljs, visa att kategorier kan överlappa utan att bli samma.",
    "Nästa vecka återkallar eleverna definitionerna och analyserar ett nytt exempel.",
  ),
  "religionskunskap-4-6-2": p(
    "Eleverna jämför två religiösa praktiker som fasta paket och skriver att alla anhängare utför dem på samma sätt.",
    [6, 5, 9, 10],
    [
      "Använd fyra korta förstapersonskällor från namngivna personer om bön eller fasta i två traditioner. Ange ålder, plats och sammanhang när det är relevant.",
      "Modellera jämförelsedimensionerna tid, syfte, form och individuell variation. Jämför samma dimension i båda praktikerna.",
      "Eleverna fyller en tabell och märker varje uppgift med källan, så att ett individuellt exempel inte görs till universell regel.",
      "De skriver en likhet och skillnad samt en variation inom vardera traditionen.",
    ],
    "Eleverna granskar meningen ”Muslimer fastar och kristna gör det inte” och skriver om den så att både saklig skillnad och variation framgår.",
    "Om jämförelsen blir alla eller inga, återgå till källornas räckvidd. Om variationen syns, diskutera hur sammanhang kan påverka praktiken.",
    "Senare jämför eleverna två nya praktiker utan den färdiga dimensionstabellen.",
  ),
  "religionskunskap-7-9-1": p(
    "Eleverna förklarar en persons handling direkt med ”religionen säger” och skiljer inte individens tolkning, gruppens normer och traditionens texter eller historia.",
    [6, 7, 9, 10],
    [
      "Ge ett konkret fall med intervju, gruppregel och ett textutdrag som inte helt överensstämmer. Håll källorna tydligt åtskilda.",
      "Modellera tre nivåer: individ, grupp eller organisation och bred tradition. Visa hur ett påstående kan stödjas på en nivå men inte generaliseras till de andra.",
      "Eleverna märker varje belägg I, G eller T och rättar en förklaring som gör individens val till regel för alla.",
      "De skriver en flernivåförklaring där minst två nivåer samspelar och en alternativ icke-religiös faktor nämns.",
    ],
    "Ge ett nytt påstående. Eleverna anger vilken nivå källan stöder och vilken ytterligare källa som behövs för en bredare slutsats.",
    "Om traditionen behandlas som en aktör med en röst, återgå till källnivån. Om nivåerna skiljs, analysera makt och variation inom gruppen.",
    "Nästa vecka använder eleverna nivåerna på ett nytt fall utan bokstavsmallen.",
  ),
  "religionskunskap-7-9-2": p(
    "Eleverna väljer först vad de själva tycker i ett dilemma och sätter sedan etiketten konsekvensetik eller pliktetik på samma argument.",
    [6, 7, 5, 9],
    [
      "Använd ett avgränsat dilemma om att bryta ett löfte för att hjälpa någon. Ange de handlingsalternativ och fakta som får användas.",
      "Modellera konsekvensetik som bedömning av följder och pliktetik som bedömning av handling, regel och universaliserbarhet. Dra två separata argumentkedjor.",
      "Eleverna får sex argument och sorterar dem efter vilken premiss som bär slutsatsen, inte efter vilken slutsats de gillar.",
      "De analyserar dilemmat med båda modellerna och pekar ut vilken ytterligare fakta respektive modell behöver.",
    ],
    "Ge en ändrad omständighet. Eleverna förklarar om och varför den påverkar konsekvensetiskt respektive pliktetiskt resonemang.",
    "Om samma argument återkommer under båda rubrikerna, synliggör premissen. Om modellerna används korrekt, lägg till en konflikt inom en modell.",
    "Senare analyserar eleverna ett nytt dilemma och återkallar själva de centrala frågorna för modellerna.",
  ),
  "religionskunskap-gymnasiet-1": p(
    "Eleverna behandlar religiös identitet som en fast etikett som ensam förklarar personens val och bortser från kön, generation, migration, klass och situation.",
    [6, 9, 10, 7],
    [
      "Använd två längre intervjuer med personer som delar religiös tillhörighet men beskriver identitet och praktik olika. Ange intervjusituation och bakgrund.",
      "Modellera en identitetskarta med flera samtidiga dimensioner och skilj personens egen förklaring från analytiska tolkningar.",
      "Eleverna markerar belägg för samspel, konflikt eller situationsberoende och formulerar två möjliga förklaringar utan att reducera individen till en kategori.",
      "De jämför fallen och skriver vilken variation materialet visar samt vad två intervjuer inte kan säga om en hel grupp.",
    ],
    "Eleverna skriver en analys med minst två identitetsdimensioner, ett citatnära belägg och en uttrycklig begränsning av slutsatsen.",
    "Om religion blir enda orsak, pröva intervjupersonens egna andra förklaringar. Om analysen är flerdimensionell, diskutera hur intervjusituationen kan påverka svaret.",
    "Vid nästa material gör eleverna identitetskartan själva och jämför utan färdiga dimensioner.",
  ),
  "religionskunskap-gymnasiet-2": p(
    "Eleverna redogör för konsekvensetik, pliktetik och dygdetik var för sig men använder inte teoriernas olika bedömningsgrunder på samma fall.",
    [6, 7, 9, 10],
    [
      "Avgränsa ett fall om vårdprioritering med två handlingsalternativ och nödvändiga fakta. Skilj faktauppgifter från värdepremisser.",
      "Modellera tre analysfrågor: följder och berörda, plikt eller rättighet samt vilken karaktär och praktisk klokhet handlingen uttrycker.",
      "Eleverna skriver en argumentkedja per teori och markerar exakt var teorins premiss påverkar slutsatsen.",
      "Lägg till en ny uppgift som ändrar en följd men inte plikten. Eleverna prövar vilka teorier som rimligen ändrar bedömning och varför.",
    ],
    "Eleverna jämför teoriernas slutsats, styrka och blinda fläck i just fallet. En allmän teoriredogörelse utan tillämpning räcker inte.",
    "Om teorierna bara får olika rubriker men samma argument, återgå till den bärande premissen. Om skillnaden är tydlig, pröva en intern invändning mot varje teori.",
    "Senare analyserar eleverna ett nytt komplext fall utan de tre analysfrågorna utskrivna.",
  ),
};
